"""Compile reviewed public institutional cases; no network or model calls.

Each row is an independently identifiable platform, not a mention in the news.
Facts are paraphrases; constraints/transfer are explicitly editorial analysis.
The short source excerpts are for field-level audit, not a copied publication.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-10-09"
def bi(zh, en): return {"zh": zh, "en": en}

# id, province, city, title, English title, archetype, sector, URL, publisher,
# overview, participants, mechanism, documented practice, interpretation, action.
ROWS = [
 ("ssl_factory","GD","东莞市","松山湖材料实验室创新样板工厂","Songshan Lake Materials Laboratory pilot factory","pilot","materials",
 "https://www.sslab.org.cn/core/factory","松山湖材料实验室",
 bi("以创新样板工厂承接材料科研成果的中试和产业化，方向包括锂电材料、晶硅光伏、水系锌电池及碳化硅。","A pilot-factory division develops materials technologies toward industrial use, including battery materials, crystalline-silicon photovoltaics, aqueous zinc batteries and silicon carbide."),
 bi("松山湖材料实验室、引进的科研团队及产业化企业。","The laboratory, recruited research teams and commercialisation companies."),
 bi("将科研团队、工程化设施与新设企业连接，开展材料工艺放大和产业转化。","Research teams, engineering facilities and newly formed companies are connected for process scale-up and technology transfer."),
 bi("官网按技术方向列出创新样板工厂团队，涉及锂离子电池材料中试、高效晶硅光伏及锌基电池。","The official division page lists teams for lithium-ion materials piloting, high-efficiency silicon photovoltaics and zinc batteries."),
 bi("材料性能、工艺稳定性和客户验证是不同关口，不能以孵化企业数量替代批量制造能力。","Material performance, process stability and customer qualification are separate gates; company counts do not measure manufacturing readiness."),
 bi("围绕本地材料产业建立可共享的工艺验证环节，并以客户验证和重复生产结果决定后续支持。","Share process-validation capabilities around local materials industries and condition follow-on support on customer qualification and repeatable production.")),
 ("giri","GD","东莞市","广东省智能机器人研究院","Guangdong Institute of Intelligent Robotics","cluster","manufacturing",
 "https://ssl.dg.gov.cn/dgssh/tzpd/cystq/jqr/content/post_3199035.html","东莞松山湖管委会",
 bi("面向机器人与智能制造，将研发、公共试验、企业孵化和投资服务配置在同一机构。","A robotics institute combines R&D, public testing, incubation and investment services for intelligent manufacturing."),
 bi("东莞市政府、研究团队、装备应用企业与投资孵化平台。","Dongguan government, research teams, equipment users and incubation/investment platforms."),
 bi("围绕3C制造需求组织机器人、机器视觉、激光器和工业数据开发，公共试验与孵化平台承接企业应用。","Robotics, vision, lasers and industrial-data development address electronics manufacturing, supported by testing and incubation."),
 bi("松山湖官方2020年介绍列出七类平台及面向企业的智能装备应用；这些是该时点的机构实践。","A 2020 official profile records seven platform functions and equipment applications for firms; these are historical observations."),
 bi("依赖制造企业持续提出可验证的工艺需求，基金与公共试验应分别核算绩效。","The arrangement needs verifiable industrial process demand; funds and public testing require separate performance accounts."),
 bi("由制造企业给出验收场景，研究院负责技术组合与试验；公共资金支持共性平台而非替代企业订单。","Let manufacturers specify acceptance scenarios while the institute integrates and tests technologies; public funding should support shared capabilities rather than replace orders.")),
 ("siat","GD","深圳市","深圳先进院产业创新协同","SIAT industry-oriented research collaboration","intermediary","biomanufacturing",
 "https://www.siat.ac.cn/jggl/jgjj/","中国科学院深圳先进技术研究院",
 bi("中国科学院、深圳市与香港中文大学共建科研机构，以研究平台连接医疗器械和生物制造产业创新。","CAS, Shenzhen and the Chinese University of Hong Kong jointly established SIAT, linking research to medical-device and biomanufacturing innovation."),
 bi("中国科学院、深圳市政府、香港中文大学及产业创新中心。","CAS, Shenzhen government, CUHK and industrial innovation centres."),
 bi("以科研平台为基础，牵头组建高性能医疗器械创新中心和生物制造产业创新中心。","Research capabilities underpin the high-performance medical-device and biomanufacturing innovation centres led by SIAT."),
 bi("机构简介明确记载三方共建关系及两类产业创新中心，不将中心设立等同于产品成功。","The institutional profile documents the founding partnership and industrial centres; their establishment is not evidence of product success."),
 bi("医工和生物制造转化需要验证场景、质量控制及专业监管能力，不能仅复制组织名称。","Medical and biomanufacturing translation also require validation settings, quality control and regulatory capabilities."),
 bi("围绕产业共性难题建设专业研发中介，将临床或生产验证责任落实到合作方。","Build specialised intermediaries around shared industrial challenges and allocate clinical or production validation responsibilities to partners.")),
 ("scici","GD","东莞市","华南协同创新研究院","South China Institute of Collaborative Innovation","cluster","materials",
 "https://www.scici.cn/about.aspx?AboutCateId=65","华南协同创新研究院",
 bi("东莞市与华南理工大学共建独立法人研究院，以地方产业需求连接高校技术资源与企业。","Dongguan and South China University of Technology jointly established an institute connecting university capabilities with local industrial demand."),
 bi("东莞市政府、华南理工大学、科研团队及产业合作方。","Dongguan government, SCUT, research teams and industrial partners."),
 bi("政府与高校共建载体，结合科学研究、技术开发、成果转化及仪器共享服务。","A city–university platform combines research, technology development, transfer and shared instrumentation."),
 bi("官网记载2012年底挂牌，具备国家级科技企业孵化器和科研仪器设备共享管理等平台资质。","The official profile records establishment in late 2012 and qualifications for incubation and shared research equipment."),
 bi("校地共建能引入知识，但是否转化取决于企业技术吸收与持续合作。","University–city partnerships bring knowledge; translation still depends on firms' absorptive capacity and sustained cooperation."),
 bi("把本地产业问题转为可签约的研发任务，并用设备使用与技术服务记录检验需求。","Turn local industrial problems into contracted R&D tasks and verify demand through equipment use and service records.")),
 ("gdut_cnc","GD","佛山市","广工大数控装备协同创新研究院","GDUT CNC equipment collaborative institute","cluster","manufacturing",
 "https://www.gdut.edu.cn/info/1709/7193.htm","广东工业大学",
 bi("校地共建数控装备研发载体，将运动控制、机器人和3D打印团队接入佛山制造产业集群。","A university–government platform connects motion-control, robotics and 3D-printing teams with Foshan manufacturing clusters."),
 bi("广东工业大学、省市区政府、固高科技等企业及研发团队。","GDUT, provincial and local governments, firms including Googol Technology, and research teams."),
 bi("地方提供建设条件，高校负责经营管理；企业与高校团队共同开发制造装备。","Local authorities provide facilities and start-up support; the university manages the institute and teams co-develop equipment with firms."),
 bi("大学2015年报道记载固高科技与校内团队合作，并列出精密装备、机器人与3D打印创新中心。","A 2015 university account documents Googol–university collaboration and centres for precision equipment, robotics and 3D printing."),
 bi("报道属于历史案例，不能推定今天的团队数量或收入；适配依赖可服务的制造客户。","This is a historical case, not a current headcount or revenue claim; adaptation needs manufacturing customers."),
 bi("以现有装备需求组织校企联合团队，先验证企业持续付费需求再扩建设施。","Organise university–firm teams around equipment demand and verify recurring willingness to pay before expanding facilities.")),
 ("icost","GD","广州市","广东腐蚀科学产业协同研究","Guangdong corrosion-science industrial collaboration","intermediary","materials",
 "https://www.icost.ac.cn/rcdw/hyfmzfsfhtc/","广东腐蚀科学与技术创新研究院",
 bi("面向核电、长输管道和海洋结构等工程，研究材料环境失效并提出寿命改善的控制参数。","Research addresses environmentally assisted failure in nuclear, pipeline and marine structures and identifies parameters for longer service life."),
 bi("研究院腐蚀与评定团队及重大工程材料使用方。","The institute's corrosion assessment team and users of engineering materials."),
 bi("把材料微观表征、环境和载荷分析连接到工程失效诊断及材料工艺改进。","Microstructural characterisation, environmental analysis and loading are linked to failure diagnosis and process improvement."),
 bi("团队官方介绍明确列出核电、长输管道、海洋结构等研究对象及全流程失效因素分析。","The official team profile identifies nuclear, pipeline and marine applications and analysis of failure factors across the production-to-service chain."),
 bi("实验室试验需要与服役条件对应，寿命推断不能脱离环境、载荷和材料批次。","Laboratory tests must match service conditions; life predictions depend on environment, loading and material batch."),
 bi("支持跨企业共享的材料可靠性评价能力，保留试验条件和适用边界而非只发布合格结论。","Support shared reliability assessment and preserve test conditions and applicability limits rather than only pass/fail labels.")),
 ("tsinghua_sz_storage","GD","深圳市","深圳清华研究院储能材料技术服务","Shenzhen Tsinghua storage-materials laboratory","intermediary","battery",
 "https://www.tsinghua-sz.edu.cn/join/detail/17","深圳清华大学研究院",
 bi("先进储能材料及器件实验室围绕电化学材料和储能器件开展共性技术研发，并向企业提供技术服务。","The advanced storage materials laboratory develops shared electrochemical-material and device technologies and provides technical services to firms."),
 bi("深圳清华大学研究院储能材料实验室及企业合作方。","The Shenzhen Tsinghua storage-materials laboratory and industrial collaborators."),
 bi("从电子化学品、超级电容器及锂电材料研究延伸到成果产业化和企业技术支持。","Work links electronic chemicals, supercapacitors and lithium-battery materials to commercialisation and technical support."),
 bi("研究院2021年公开实验室介绍列出相关材料、器件及为企业服务的职能。","A public 2021 institutional description specifies the materials, devices and industrial-service function."),
 bi("公开材料说明研究方向和职能，未提供完整的转化收入或企业服务效果。","The source establishes scope and functions, not comprehensive transfer revenues or service outcomes."),
 bi("按企业材料验证问题设定技术合同，分别考核研发交付、许可和工程应用。","Contract around firms' materials-validation problems and assess research delivery, licensing and engineering use separately.")),
 ("songshan_medeng","GD","东莞市","松山湖医工融合创新中心","Songshan Lake medical-engineering innovation centre","cluster","biomanufacturing",
 "https://news.gdmu.edu.cn/info/1005/56698.htm","广东医科大学",
 bi("广东医科大学与东莞理工学院共建医工平台，通过医院需求、工程研发及企业合作开发医疗设备原型。","Guangdong Medical University and Dongguan University of Technology jointly connect medical needs, engineering and firms to develop device prototypes."),
 bi("广东医科大学、东莞理工学院、医疗场景合作方及华为等企业。","The two universities, medical-setting partners and firms including Huawei."),
 bi("两校共同提供资金、场地和人员，围绕康复器具、智慧医疗及生物材料开展联合研发。","The universities contribute funds, facilities and personnel for rehabilitation devices, smart healthcare and biomaterials."),
 bi("大学发布的2025年纪实记录医用物流机器人等样机及染色体核型分析、口腔导航等七台套原型设备。","The university's 2025 account records medical-logistics prototypes and seven prototype devices including karyotype analysis and dental navigation."),
 bi("原型不等于获批产品，医工合作必须继续经过临床验证与注册评价。","Prototypes are not approved products; clinical validation and regulatory assessment remain necessary."),
 bi("在研发早期明确临床需求、工程验收与注册路径，避免只考核样机数量。","Specify medical needs, engineering acceptance and regulatory pathways early rather than rewarding prototype counts alone.")),
 ("zju_shaoxing","ZJ","绍兴市","浙江大学绍兴研究院","Zhejiang University Shaoxing institute","cluster","manufacturing",
 "https://shaoxing.zju.edu.cn/index.php?a=lists&c=index&catid=19&m=content","浙江大学绍兴研究院",
 bi("浙江大学与绍兴市共建研究院，把集成电路、新材料等研发和地方产业服务连接起来。","Zhejiang University and Shaoxing jointly connect integrated-circuit and materials research with local industrial services."),
 bi("浙江大学、绍兴市政府、研发团队及产业合作方。","Zhejiang University, Shaoxing government, research teams and industrial collaborators."),
 bi("校地共建独立法人机构，公共技术平台承接检测、传感器和封装等产业需求。","An independent city–university institute uses shared technical platforms for testing, sensors and packaging."),
 bi("官网列出微电子功率检测、MEMS传感器和集成电路先进封装三类公共技术平台。","The official profile lists public platforms for power-device testing, MEMS sensors and advanced IC packaging."),
 bi("平台跨多个方向，实际适配取决于本地企业需求与设备使用，而非高校品牌。","Multiple technology domains require demonstrated local demand and equipment use, not university branding alone."),
 bi("按产业链具体工艺缺口配置公共服务，并公开企业使用和成果交付的可比记录。","Configure services around specific value-chain gaps and retain comparable records of firm use and deliverables.")),
 ("zhejiang_tsinghua","ZJ","嘉兴市","浙江清华长三角研究院","Yangtze Delta Region Institute of Tsinghua University","intermediary","materials",
 "https://www.tsinghua-zj.edu.cn/institute/introduce","浙江清华长三角研究院",
 bi("省校共建研究院将实验室、概念验证、中试与区域产业服务连接，涉及柔性电子、陶瓷材料及氢能装备。","A province–university institute links laboratories, proof of concept, piloting and regional industrial services in flexible electronics, ceramics and hydrogen equipment."),
 bi("浙江省、清华大学、研究平台和产业合作方。","Zhejiang province, Tsinghua University, research platforms and industrial partners."),
 bi("依托省校合作组织技术研发，再以概念验证和中试平台推进工程应用。","Province–university cooperation organises research, followed by proof-of-concept and pilot platforms for engineering applications."),
 bi("官方简介列出柔性集成器件、新型陶瓷材料中试平台，以及柔性电子和氢能装备制造业创新中心。","The profile lists pilot platforms for flexible integrated devices and ceramics, plus innovation centres for flexible electronics and hydrogen equipment."),
 bi("多个平台共用研究院品牌，不应把每个平台数量相加当成独立产业成果。","Platforms share an institutional umbrella; their counts must not be added as independent industrial outcomes."),
 bi("按技术成熟阶段衔接验证与工程化，跨地区复制时明确各平台的独立交付责任。","Link validation and engineering by maturity stage and assign distinct delivery responsibilities when replicating across regions.")),
 ("zhejiang_lab","ZJ","杭州市","之江实验室智能计算协同与成果转化","Zhejiang Lab intelligent-computing collaboration","mission","digital",
 "https://www.zjsjw.gov.cn/gongzuodongtai/xunshixuncha/202411/t20241125_23060530.shtml","浙江省纪委省监委",
 bi("之江实验室以智能计算任务牵引高校与企业协同，并通过成果转化平台和基金推进应用。","Zhejiang Lab organises university–industry cooperation around intelligent computing and uses a transfer platform and fund for applications."),
 bi("之江实验室、浙江大学、杭州电子科技大学、浙大城市学院及产业伙伴。","Zhejiang Lab, Zhejiang University, Hangzhou Dianzi University, Zhejiang University City College and industrial partners."),
 bi("联合建设研究与算力平台，以之科控股和成果转化基金衔接科研成果与应用。","Joint research and computing platforms connect to applications through Zhike Holdings and a technology-transfer fund."),
 bi("2024年公开通报记载合作平台、材料智能计算研究及成果转化评价安排。","A 2024 public account documents collaborative platforms, materials intelligent-computing research and transfer-evaluation arrangements."),
 bi("大型计算设施具有固定成本；任务导向应防止与企业近期应用需求脱节。","Large computing facilities carry fixed costs; mission-oriented work must retain links to actual industrial needs."),
 bi("对共性算力与应用项目分别设定预算和验收指标，以真实任务检验平台使用价值。","Budget and evaluate shared computing separately from application projects, using real tasks to test platform value.")),
 ("sjtu_shaoxing","ZJ","绍兴市","上海交大绍兴新能源与分子工程研究院","SJTU Shaoxing new-energy and molecular-engineering institute","intermediary","battery",
 "https://www.sjtu.sx.cn/","上海交通大学绍兴新能源与分子工程研究院",
 bi("地方举办、高校运营的研究院围绕电池、氢能及分子工程建立研发和公共测试平台。","A locally established, university-operated institute develops battery, hydrogen and molecular-engineering R&D and shared testing."),
 bi("绍兴滨海新区管委会、上海交通大学化学化工学院及研发合作方。","Shaoxing Binhai New Area, SJTU's chemistry and chemical-engineering school and research partners."),
 bi("以先进电池、公共测试、智慧能源、分子工程和氢应用五类平台连接学科成果与工程需求。","Five platforms link disciplinary research with engineering needs in batteries, testing, smart energy, molecular engineering and hydrogen applications."),
 bi("官网列出五类平台及新能源材料、动力与储能电池等研究方向。","The institutional site lists the five platforms and research on energy materials and traction/storage batteries."),
 bi("材料研发与规模生产之间仍需企业工程组织和市场验证，平台设置不能替代两者。","Materials research still needs firms' engineering organisation and market validation before scalable production."),
 bi("围绕电化学材料测试和工程转化设定校地分工，避免用同一口径评价基础研究与生产放大。","Allocate university–local roles around electrochemical testing and translation, with separate criteria for research and production scale-up.")),
 ("tju_idim","ZJ","绍兴市","天津大学浙江国际创新设计与智造研究院","Tianjin University Zhejiang design and manufacturing institute","cluster","manufacturing",
 "https://idim.tju.edu.cn/gywm.htm","天津大学浙江国际创新设计与智造研究院",
 bi("天津大学与绍兴市共建独立法人研究院，结合创新设计、智能制造、企业共建研发与孵化。","Tianjin University and Shaoxing jointly established an institute combining design, intelligent manufacturing, joint R&D and incubation."),
 bi("天津大学、绍兴市政府、入驻团队和企业联合研发中心。","Tianjin University, Shaoxing government, resident teams and joint industrial R&D centres."),
 bi("以开放办院方式建设企业共建研发中心和成果转化工作站，面向地方产业需求承接项目。","Open collaboration supports joint industrial centres and a transfer station responding to local industrial demand."),
 bi("官方简介记载2021年成立，并列出创新设计、低碳智造及电子信息等孵化方向。","The profile records establishment in 2021 and incubation in design, low-carbon manufacturing and electronics."),
 bi("研究院与天津大学浙江研究院（绍兴）为不同载体，名称近似不能合并统计。","This is distinct from Tianjin University's other Shaoxing institute; similar names must not be merged."),
 bi("围绕企业设计和工艺改进需求建立联合任务，明确知识产权与产业化责任。","Create joint tasks around firms' design and process needs, with clear IP and commercialisation responsibilities.")),
 ("tju_shangyu","ZJ","绍兴市","天津大学浙江研究院绍兴化工协同","Tianjin University Zhejiang Shaoxing chemical collaboration","intermediary","materials",
 "https://tjuzj.com/ykjj.html","天津大学浙江研究院（绍兴）",
 bi("在上虞布局新材料、精细化学品及智能化工研发，以检测、中试和企业合同连接高校与化工产业。","Located in Shangyu, the institute connects university research with chemicals industries through testing, piloting and industrial contracts."),
 bi("天津大学、绍兴上虞地方政府、科研团队及合作企业。","Tianjin University, local Shangyu authorities, research teams and firms."),
 bi("采用多团队、多专业、多中心的协同方式，提供检测、中试和培训公共服务。","Multidisciplinary teams and centres provide shared testing, piloting and training."),
 bi("官方简介记载2019年落地和2025年二期合作，并列出化工合成、安全与分离工程研究中心。","The profile records establishment in 2019, renewed cooperation in 2025, and centres for synthesis, safety and separation engineering."),
 bi("化工中试需要安全、环保和工艺放大的联动条件，不能照搬一般孵化空间。","Chemical piloting needs integrated safety, environmental and scale-up conditions, not generic incubator space."),
 bi("把安全与环境验证纳入中试准入和合同验收，优先复用已有化工产业设施。","Include safety and environmental validation in pilot admission and acceptance, reusing existing chemical-industry infrastructure where suitable.")),
 ("zjut_shengzhou","ZJ","绍兴市","浙江工业大学嵊州研究院厨电协同","ZJUT Shengzhou kitchen-appliance collaboration","cluster","manufacturing",
 "https://www.most.gov.cn/dfkj/zj/zxdt/202301/t20230128_184396.html","科学技术部",
 bi("研究院深耕嵊州厨房电器产业，与厨具企业合作改进集成灶风机系统。","The institute works with Shengzhou kitchen-appliance firms on integrated-cooker fan systems."),
 bi("浙江工业大学嵊州研究院和当地厨具企业。","ZJUT's Shengzhou institute and local kitchen-appliance firms."),
 bi("高校研究力量围绕地方产业集群的具体产品性能问题开展联合研发。","University capabilities are directed to concrete product-performance problems in a local industrial cluster."),
 bi("科技部2023年地方科技报道明确列出合作开发集成灶风机系统的实践。","A 2023 MOST regional account identifies collaborative development of integrated-cooker fan systems."),
 bi("单个产品案例能说明需求组织方式，不能据此推断整个浙江制造业的转化效率。","A product case illustrates demand organisation, not the efficiency of all manufacturing in Zhejiang."),
 bi("以集群企业共同工艺需求组织小型专业团队，按产品测试和企业采用评价成果。","Organise specialised teams around shared cluster needs and evaluate product tests and adoption by firms.")),
 ("buaa_hangzhou","ZJ","杭州市","北航杭州创新研究院","Beihang Hangzhou Innovation Institute","mission","digital",
 "https://hzii.buaa.edu.cn/gyyjy/yjyjs.htm","北京航空航天大学杭州创新研究院",
 bi("省、市、区与北航共建研究院，围绕低空安全、具身智能、空间智能和量子传感组织研究平台。","A province–city–district partnership with Beihang organises platforms for low-altitude safety, embodied intelligence, spatial intelligence and quantum sensing."),
 bi("北京航空航天大学、浙江省、杭州市、滨江区与研究团队。","Beihang University, Zhejiang, Hangzhou, Binjiang district and research teams."),
 bi("依托空天信息学科优势，由研究中心和前沿平台组织专业任务。","Research centres and frontier platforms organise specialist tasks using aerospace and information-science capabilities."),
 bi("官方简介明确四个研究方向及八个研究中心、十六个前沿创新平台。","The official profile specifies four directions, eight research centres and sixteen frontier platforms."),
 bi("平台数量不是产业采用率，任务与地方企业需求的连接需要单独验证。","Platform counts are not adoption rates; connections to local industrial demand require separate validation."),
 bi("将国家科技任务和地方应用场景分别设置交付节点，防止两类目标相互替代。","Set separate milestones for national research missions and local applications so one does not substitute for the other.")),
 ("nimte_daishan","ZJ","舟山市","宁波材料所岱山新材料中试基地","CNITECH Daishan materials pilot base","pilot","materials",
 "https://www.nimte.cas.cn/news/cooperation/202109/t20210930_6218218.html","中国科学院宁波材料技术与工程研究所",
 bi("岱山县与宁波材料所共建化工新材料中试基地，连接研究、工程化、示范和产品商业化。","Daishan county and CNITECH jointly develop a chemicals/materials pilot base linking research, engineering, demonstration and commercialisation."),
 bi("岱山县政府、中国科学院宁波材料所及技术转化团队。","Daishan government, CAS CNITECH and technology-transfer teams."),
 bi("基地以化工新材料为中试对象，将工程化关键技术突破与属地产业应用衔接。","Piloting focuses on new chemical materials and connects engineering breakthroughs to local industrial applications."),
 bi("2021年官方开工报道给出共建主体、中试对象和研究至商业化的转化路径。","The 2021 official groundbreaking report identifies the partners, pilot focus and research-to-commercialisation pathway."),
 bi("开工报道不证明后续投产率；中试设施需满足安全条件并有稳定项目来源。","Groundbreaking does not establish later utilisation; pilot facilities need safety conditions and sustained project demand."),
 bi("先审查中试项目管线与工程安全条件，再安排公共设施投入和运营支持。","Review the pilot pipeline and engineering safety before committing public facilities and operating support.")),
 ("graphene_centre","ZJ","宁波市","浙江石墨烯制造业创新中心","Zhejiang graphene manufacturing innovation centre","pilot","materials",
 "https://cnitech.cas.cn/news/cooperation/202107/t20210701_6124804.html","中国科学院宁波材料技术与工程研究所",
 bi("宁波材料所联合产业链企业及资本共建公司化创新中心，推进石墨烯研发、中试和应用孵化。","CNITECH, value-chain firms and investors jointly established a corporate centre for graphene research, piloting and application incubation."),
 bi("宁波材料所、骨干企业、上下游企业、投资基金与产业资本。","CNITECH, anchor firms, upstream/downstream firms, investment funds and industrial capital."),
 bi("共同出资运营研发与中试平台，将研究能力接入应用企业和产业资本。","Joint investment operates research/pilot facilities connecting scientific capabilities to application firms and industrial capital."),
 bi("2021年官方验收报道记载公司化运营主体，以及对成果转化公司和应用孵化项目的现场考察。","An official 2021 acceptance account documents the corporate operator and inspection of transfer companies and incubated applications."),
 bi("通过验收说明建设阶段得到认可，不等于石墨烯产品已形成普遍市场需求。","Acceptance recognises a development stage, not general market demand for graphene products."),
 bi("以应用企业试用、材料批次一致性和共同出资责任约束中心运行。","Govern the centre through application trials, batch consistency and co-investors' responsibilities.")),
 ("nimte_poc","ZJ","宁波市","中科新材概念验证中心","CNITECH new-materials proof-of-concept centre","intermediary","materials",
 "https://www.nimte.ac.cn/news/media/202311/t20231116_6933628.html","中国科学院宁波材料技术与工程研究所",
 bi("概念验证中心将新材料实验线、产业伙伴、专项资金及技术商业导师组合，用于验证早期成果的应用价值。","A materials proof-of-concept centre combines experimental lines, industrial partners, dedicated funding and technical/business mentors."),
 bi("宁波材料所、浙江工研院发展有限公司、产业企业及技术与商业导师。","CNITECH, Zhejiang Industrial Technology Institute Development Company, firms and technical/business mentors."),
 bi("以产业调研、可行性论证、知识产权布局和企业结对，把科学成果转成可检验的商业假设。","Industry research, feasibility work, IP planning and firm matching turn research into testable commercial hypotheses."),
 bi("研究所刊载的2023年成立报道明确记载运营主体、专项资金与企业一对一结对安排。","The institute's 2023 establishment account identifies the operator, dedicated funds and one-to-one matching with firms."),
 bi("这是研究所刊载的媒体报道，资金安排和服务设置并不等于项目已实现商业成功。","This is a media account hosted by the institute; funding and services do not establish commercial success."),
 bi("用小额分阶段验证确定客户、成本和工艺假设，失败项目允许退出而不强求设立企业。","Use small staged tests for customer, cost and process assumptions, allowing unsuccessful projects to exit without forcing company formation.")),
 ("ustc_iat","AH","合肥市","中国科大先研院技术熟化与联合研发","USTC Institute of Advanced Technology joint R&D","intermediary","digital",
 "https://iat.ustc.edu.cn/iat/yfjgjj.html","中国科学技术大学先进技术研究院",
 bi("先研院以工程中心和企业联合实验室组织技术开发、熟化、中试与成果验证。","The institute uses engineering centres and joint industrial laboratories for development, maturation, piloting and validation."),
 bi("中国科大先研院、科研团队及行业龙头企事业单位。","USTC IAT, research teams and industrial/public-sector partners."),
 bi("科研团队组建技术开发和产业运营队伍，联合实验室按企业需求开展定制化研发。","Research teams form technical and commercialisation units; joint laboratories deliver demand-led customised R&D."),
 bi("官网研发机构简介明确记载技术熟化、中试放大、成果验证和定制化开发职能。","The official R&D profile documents maturation, scale-up, validation and customised development functions."),
 bi("联合实验室数量不能说明合同履约质量，需要检查企业投入、验证及持续使用。","Joint-laboratory counts do not establish delivery quality; investment, validation and continued use need checking."),
 bi("将联合实验室支持与企业任务、交付及后续使用挂钩，避免重挂牌轻运营。","Tie joint-laboratory support to firm tasks, deliverables and continued use rather than establishment alone.")),
 ("tsinghua_eiri","SC","成都市","清华四川能源互联网研究院成果转化","Tsinghua Sichuan Energy Internet Research Institute transfer","intermediary","grid",
 "https://www.tsinghua-eiri.org/conversion.aspx?t=80","清华四川能源互联网研究院",
 bi("研究院围绕能源互联网开展科技成果转化，公开列出电力传感、仿真软件及换流技术的许可和作价入股。","The institute transfers energy-internet technologies and publishes licensing/equity routes for sensing, simulation and converter technologies."),
 bi("研究院、科研团队、科技型企业及地方产业合作方。","The institute, research teams, technology firms and regional industrial partners."),
 bi("通过普通许可或作价入股，把科研技术与新企业、既有企业的工程应用连接。","Non-exclusive licensing and equity contributions connect research to engineering applications in new and existing firms."),
 bi("官网处置清单列出磁场电流微传感技术作价入股，以及换流阀、电力系统仿真等技术的普通许可。","The public transfer register lists an equity transaction for sensing and non-exclusive licences for converters and power-system simulation."),
 bi("处置方式可以核查，但许可签署不自动证明技术采用规模或商业回报。","Transfer routes are documented; licensing does not by itself establish adoption scale or returns."),
 bi("公布可追溯的技术处置清单，按许可实施和工程使用评价转化，而不是只数协议。","Maintain traceable transfer registers and evaluate implementation and engineering use, not agreements alone.")),
 ("stanford_otl","US","Redwood City","斯坦福大学技术许可与创业支持","Stanford technology licensing and startup support","venture","general",
 "https://otl.stanford.edu/","Stanford University",
 bi("技术许可办公室把高校发明披露、技术检索、许可、早期转化资金及产业合同服务连接。","OTL links invention disclosure, technology discovery, licensing, early transfer funding and industrial contracting."),
 bi("斯坦福研究人员、技术许可办公室、产业合同办公室及潜在被许可企业。","Stanford researchers, OTL, the Industrial Contracts Office and prospective licensees."),
 bi("通过技术目录匹配被许可方，创业资源和HIT基金支持早期研究向应用推进。","A technology catalogue matches licensees while startup resources and the HIT Fund support early translation."),
 bi("官方网站提供可许可技术目录、创业资源、HIT基金及产业合同办公室入口。","The official site provides a licensable-technology catalogue, startup resources, HIT Fund and industrial-contracting services."),
 bi("这是硅谷科研创业网络的一个节点，不代表硅谷全体企业，也不能将许可额等同于区域绩效。","This is one node in Silicon Valley's research–venture network, not the whole ecosystem or a regional performance measure."),
 bi("借鉴发明披露、专业许可和利益冲突审查接口，而非机械复制园区与风险投资规模。","Adapt disclosure, professional licensing and conflict-of-interest interfaces rather than copying park or venture-fund scale.")),
 ("startx","US","Palo Alto","StartX科研创业者互助网络","StartX founder support network","venture","general",
 "https://sen.stanford.edu/startx","Stanford Entrepreneurship Network",
 bi("StartX以非营利创业者网络提供导师、教育和资源支持，不向参与企业收取费用或索取股权。","StartX provides mentorship, education and resources through a nonprofit founder network without charging fees or taking equity."),
 bi("StartX、斯坦福背景创业者、导师及创业社群。","StartX, Stanford-affiliated founders, mentors and the founder community."),
 bi("以持续的同行支持和专业导师降低创业早期的信息与能力障碍。","Ongoing peer support and mentoring address early-stage information and capability barriers."),
 bi("斯坦福创业网络官方介绍说明导师、教育和社区支持及不收费、不取股权的安排。","Stanford's entrepreneurship network documents mentoring, education, community support and the no-fee/no-equity arrangement."),
 bi("成员资格和既有网络是前提，不能推定对所有后发地区企业同样有效。","Eligibility and existing networks are prerequisites; equal effectiveness in other regions cannot be assumed."),
 bi("建设专业导师和同行服务，区分孵化服务与商业投资，不以入驻率替代创业质量。","Build mentoring and peer services, separate incubation from investment, and avoid treating occupancy as venture quality.")),
 ("aist_solutions","JP","东京都","日本AIST Solutions产业桥接","Japan AIST Solutions industrial bridging","intermediary","general",
 "https://www.aist-solutions.co.jp/aisol_startup/","AIST Solutions",
 bi("AIST Solutions与日本产业技术综合研究所协同，从工程、市场、加速和资本等环节支持研究型初创企业。","AIST Solutions works with AIST to support research-based startups through engineering, marketing, acceleration and capital."),
 bi("AIST Solutions、日本产业技术综合研究所及获支持初创企业。","AIST Solutions, AIST and supported research-based startups."),
 bi("把公共研究机构的技术能力与专业化商业支持连接，协同推进技术的事业化。","Public-research capabilities connect to specialised commercial support for technology deployment."),
 bi("官方创业支持页列出工程、营销、商业加速和资本增强等支持环节。","The official startup-support page identifies engineering, marketing, business acceleration and capital support."),
 bi("该机构是日本桥接机制的案例，并不代表所有日本企业或行业采用同一模式。","This exemplifies a Japanese bridging mechanism, not a single model used by all Japanese firms or sectors."),
 bi("将公共研究资源与专业转化职能分工，依据具体企业技术瓶颈选择支持方式。","Separate public-research and professional transfer responsibilities and match support to firms' technical bottlenecks.")),
]

def main():
    cases, sources = [], []
    for key, region, city, zh, en, model, sector, link, publisher, summary, actors, mechanism, observed, constraints, transfer in ROWS:
        cid, sid = "oi_"+key, "s_regional_"+key
        source = {"id":sid,"url":link,"title":zh+"：机构与协同机制", "publisher":publisher,
                  "language":"en" if region=="US" else "ja" if region=="JP" else "zh",
                  "published_date":None,"reviewed_at":DATE,"access":"public_metadata_and_paraphrase","source_role":"primary"}
        if key=="nimte_poc": source["source_role"]="institution_hosted_media"
        sources.append(source)
        cases.append({"id":cid,"title":bi(zh,en),"countries":[region if region in {"US","JP"} else "CN"],
          "scope":"national","sector":bi({"materials":"新材料与工程验证","manufacturing":"先进制造","digital":"数字技术与智能系统","biomanufacturing":"医疗与生物制造","battery":"电池与储能","grid":"能源互联网","general":"跨领域技术转化"}[sector],sector.replace('_',' ')),
          "sector_key":sector,"aliases":[zh,en],"challenges":["factor","adaptation"],
          "modes":["testbed" if model=="pilot" else "incubation" if model=="venture" else "translation"],
          "institutions":["research"],"factors":["knowledge","talent","market"],
          "start_year":None,"end_year":None,"review_status":"reviewed",
          "summary":summary,"actors":actors,"mechanism":mechanism,"observed":observed,
          "constraints":constraints,"transfer":transfer,
          "evidence":[{"source_id":sid,"supports":["summary","actors","mechanism","observed"]}],
          "research_annotation":{"primary_model":model,"country":region if region in {"US","JP"} else "CN",
             "province":"CN-"+region if region not in {"US","JP"} else None,"city":city if region not in {"US","JP"} else None,
             "grain":"platform","basis":"manual_source_review","reviewed_at":DATE,
             "interpretation_fields":["constraints","transfer","primary_model"]}})
    out={"schema_version":"1.0","reviewed_at":DATE,"cases":cases,"sources":sources,
         "sector_taxonomy":{"materials":bi("新材料与工程验证","Materials and engineering validation"),
          "manufacturing":bi("先进制造","Advanced manufacturing"),"digital":bi("数字技术与智能系统","Digital and intelligent systems"),
          "biomanufacturing":bi("医疗与生物制造","Medical and biomanufacturing"),"general":bi("跨领域技术转化","Cross-sector technology transfer")}}
    target=ROOT/"config/open_innovation_regional_cases.json"
    target.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"new_cases":len(cases),"China":sum(c["countries"]==["CN"] for c in cases)},ensure_ascii=False))

if __name__=="__main__": main()
