"""Reviewed expansion of thin regions; no network/model calls in daily builds.

Each record denotes a named collaboration, service platform or programme, not
a news mention. Facts are paraphrased from the cited official page or indexed
official excerpt; constraints and transfer lessons are editorial interpretation.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-10-09"
CASES, SOURCES, PROFILES = [], [], []
SECTORS = json.loads((ROOT/'config/open_innovation_coverage.json').read_text(encoding='utf-8'))['sector_taxonomy']

def bi(value):
    zh, en = value.split('|', 1)
    return {'zh':zh, 'en':en}

def add(key, country, province, city, title, model, sector, url, publisher,
        language, summary, actors, mechanism, observed, constraints, transfer,
        *, factors=('knowledge','market'), institutions=('research',), period=None):
    existing = next((s for s in SOURCES if s['url']==url), None)
    sid = existing['id'] if existing else 's_expansion_'+key
    if not existing:
        SOURCES.append(dict(id=sid,url=url,title=bi(title)['zh'],publisher=publisher,
            language=language,published_date=None,reviewed_at=DATE,
            access='public_metadata_and_paraphrase',source_role='primary',
            review_basis='official_page_text_or_indexed_official_excerpt'))
    CASES.append(dict(id='oi_'+key,title=bi(title),countries=[country],scope='national',
        sector=SECTORS[sector],sector_key=sector,aliases=list(bi(title).values()),
        challenges=['factor','adaptation'],
        modes=['testbed' if model=='pilot' else 'incubation' if model in ('venture','capacity') else 'translation'],
        institutions=list(institutions),factors=list(factors),
        start_year=period[0] if period else None,end_year=period[1] if period else None,
        review_status='reviewed',
        **{k:bi(v) for k,v in zip(('summary','actors','mechanism','observed','constraints','transfer'),
                                  (summary,actors,mechanism,observed,constraints,transfer))},
        evidence=[dict(source_id=sid,supports=['summary','actors','mechanism','observed'])],
        research_annotation=dict(primary_model=model,country=country,province=province,city=city,
            grain='platform',cohort='expansion_review',basis='manual_source_review',reviewed_at=DATE,
            interpretation_fields=['constraints','transfer','primary_model'])))

# Chinese locations follow the operating facility, not the address of a partner.
add('tyut_forming','CN','CN-SX','太原市','太原理工先进成形与智能装备中试基地|Taiyuan University forming and intelligent-equipment pilot base',
 'pilot','manufacturing','https://mc.tyut.edu.cn/info/1060/23215.htm','太原理工大学机械工程学院','zh',
 '基地连接先进成形研究、装备研发和中试转化，并与山西机电研究院开展校企对接。|The base connects forming research, equipment development and piloting, with engagement by the Shanxi electromechanical institute.',
 '太原理工大学机械工程学院、中国机械总院山西机电研究院。|Taiyuan University mechanical engineering school and CAM’s Shanxi electromechanical institute.',
 '企业实地考察中试设施，双方围绕联合科研、市场开拓和学术共建讨论合作。|Industry visits to pilot facilities support discussions on joint research, market development and academic cooperation.',
 '2026年校方记录确认中试基地已被实地参观；常态化合作属于双方后续安排。|The 2026 university account confirms a visit to the existing base; sustained cooperation is a follow-up arrangement.',
 '参观和合作意向不证明订单或技术采用。|Visits and intentions do not establish orders or adoption.',
 '把企业零件的试制性能与工艺交付列为共同验收内容。|Use industrial-part trials and process deliverables for joint acceptance.',factors=('knowledge','infrastructure','market'))
add('tyut_mining','CN','CN-SX','太原市','太原理工矿业学科产学研联盟|Taiyuan mining research–industry alliances',
 'consortium','industry','https://kyxy.tyut.edu.cn/info/1019/12437.htm','太原理工大学矿业工程学院','zh',
 '矿业学科围绕绿色安全开采、煤层气和智能采矿，与能源和装备企业建立产学研联盟。|Mining researchers organise industry alliances around safe extraction, coalbed methane and intelligent mining.',
 '太原理工大学、国家能源集团、晋能控股、太重集团、山西焦煤。|Taiyuan University, CHN Energy, Jinneng, Taiyuan Heavy Industry and Shanxi Coking Coal.',
 '企业横向研发与开放实验平台连接采矿研究、装备开发和现场问题。|Industrial research contracts and open laboratories connect mining research, equipment development and field problems.',
 '学院简介列出具名企业联盟和向行业开放实验平台的安排。|The school profile names industrial alliances and laboratory access for industry.',
 '矿业安全与生产连续性限制现场试验，合作数量不等于减排效果。|Safety and production continuity constrain trials; partnership counts are not emissions reductions.',
 '让矿山业主参与测试方案，分别验证安全、效率和环境指标。|Involve mine operators in trials and verify safety, efficiency and environmental measures separately.')
add('dairy_innovation','CN','CN-NM','呼和浩特市','乳业国家技术创新中心|National Dairy Technology Innovation Centre',
 'consortium','biomanufacturing','https://ip.nctid.cn/platform/about/about.html','乳业国家技术创新中心','zh',
 '中心由自治区承担建设责任、企业研究院承建，联合产学研力量解决乳业全链条技术问题。|The centre combines regional responsibility, a corporate research operator and research–industry collaboration across the dairy chain.',
 '内蒙古自治区、内蒙古乳业技术研究院、乳业企业及高校院所。|Inner Mongolia, its dairy technology institute, dairy firms and universities/research institutes.',
 '以一网络、四中心、三平台组织研发，并通过知识产权服务连接创新与转化。|A network, four centres and three platforms organise R&D, complemented by IP services for transfer.',
 '官方介绍确认2022年获批及呼和浩特总部布局，明确产学研共同建设。|The official profile records approval in 2022, the Hohhot headquarters and joint industry–research construction.',
 '龙头企业需求不能替代全行业竞争性技术遴选。|Anchor-firm demand should not replace competitive technology selection across the industry.',
 '明确共性研究与企业专有成果的产权边界和使用条件。|Separate shared research from proprietary results through explicit ownership and access rules.',institutions=('research','ip'))
add('baotou_rareearth','CN','CN-NM','包头市','包头稀土研究院产业协作|Baotou rare-earth institute industrial collaboration',
 'cluster','materials','https://www.baotou.gov.cn/zfxxgk/fdzdgknr/fd_jyta/bm/skxjsj/zxta/202505/t20250526_527410.html','包头市科学技术局','zh',
 '稀土研究院与当地实验室和技术平台参与成果发布、技术需求对接及稀土材料产业交流。|The institute joins local laboratories and platforms in technology disclosures, demand matching and rare-earth materials exchanges.',
 '包头稀土研究院、鹿城实验室、稀土产业企业和地方科技部门。|Baotou rare-earth institute, Lucheng Laboratory, rare-earth firms and local science authorities.',
 '专业技术机构嵌入稀土集群，以技术需求发布和路演连接研究与企业应用。|Specialist institutions are embedded in the rare-earth cluster, linking research to applications through demand calls and demonstrations.',
 '2025年政府答复列明研究院参与的学术交流与科创会客厅活动。|A 2025 government reply identifies institute participation in scientific exchanges and technology-matching events.',
 '活动和合作意向不能据此换算为量产规模。|Events and agreements cannot be converted into manufacturing output.',
 '围绕分离、功能材料和客户验证建立可追踪的工程任务。|Track engineering tasks in separation, functional materials and customer validation.')
add('ciac_pilot','CN','CN-JL','长春市','长春应化所化工新材料中试基地|Changchun applied-chemistry materials pilot base',
 'pilot','materials','https://ciac.cas.cn/xwdt/kyjz/202011/t20201120_5759321.html','中国科学院长春应用化学研究所','zh',
 '基地以生态高分子、聚烯烃和橡胶中试设施补充化学研究成果的工程化开发。|Pilot facilities for ecological polymers, polyolefins and rubber support engineering of chemical research.',
 '长春应化所、科技总公司、吉林省科技部门和工业用户。|CIAC, its technology company, Jilin science authorities and industrial users.',
 '研究所与转化企业共同建设中试中心，验收覆盖建设、运行和对外服务。|Institute and transfer company develop pilots assessed for construction, operation and external services.',
 '官方记录确认三个中试中心通过验收；本库将其整体计为一个基地。|The official account records acceptance of three centres, counted here as one pilot base.',
 '材料放大需重新验证批次和工况，不因验收而免除企业验证。|Scale-up needs batch and operating-condition tests beyond facility acceptance.',
 '将公共设备开放与具体工艺保密分开管理。|Manage public equipment access separately from confidential processes.',factors=('knowledge','infrastructure','market'))
add('sanjiang_fungi','CN','CN-JL','长春市','吉林农业大学菌物生物制造中试中心|Jilin Agricultural University fungal-biomanufacturing pilot centre',
 'pilot','biomanufacturing','https://sjlab.jlau.edu.cn/zuixindongtai/248.html','吉林农业大学三江实验室','zh',
 '中心面向菌物基材料、食药用菌加工和活性成分开发，补齐实验成果的中试验证环节。|The centre pilots fungal materials, mushroom processing and active ingredients to bridge laboratory and industrial development.',
 '吉林农业大学、食药用菌教育部工程研究中心、三江实验室及产业合作方。|Jilin Agricultural University, its mushroom engineering centre, Sanjiang Laboratory and industrial partners.',
 '依托高校工程研究中心与省实验室共同申报建设专业中试平台。|A university engineering centre and provincial laboratory jointly establish a specialised pilot platform.',
 '2026年9月官方报道确认省级中试中心备案；规模化产品仍为发展方向。|A September 2026 official account confirms provincial registration; scaled products remain a development direction.',
 '备案不代表菌物新材料已形成稳定市场。|Registration does not establish a stable market for fungal materials.',
 '在材料性能、加工成本和客户试用三方面设置验证门槛。|Set validation gates for material performance, processing cost and customer trials.',factors=('knowledge','infrastructure','market'))
add('nanchang_ev','CN','CN-JX','南昌市','南昌智能新能源汽车研究院|Nanchang intelligent new-energy vehicle institute',
 'cluster','mobility','https://www.nc.gov.cn/ncszf/jrnc/202607/d8107dee3f5442638f7326482dede945.shtml','南昌市人民政府','zh',
 '研究院把同济大学科研能力与江西汽车企业连接，围绕新能源动力、线控底盘和汽车材料孵化企业。|The institute links Tongji research with Jiangxi automotive firms and incubates ventures in powertrains, drive-by-wire and materials.',
 '南昌智能新能源汽车研究院、同济大学、江铃及孵化企业。|The Nanchang institute, Tongji University, JMC and incubated firms.',
 '新型研发机构按市场节奏开展项目决策、转化和投资，让技术进入本地产品链。|A new R&D operator combines market-facing project decisions, transfer and investment to enter local product chains.',
 '2026年政府报道列出三家孵化企业及线控底盘在江铃车型中的应用。|A 2026 government report names three incubated firms and drive-by-wire use in JMC vehicles.',
 '具体车型采用不能外推到所有孵化技术。|Adoption in specific vehicles cannot be generalised to all incubated technologies.',
 '由整车用户共同定义功能、可靠性和量产适配要求。|Let vehicle users jointly define function, reliability and production requirements.')
add('beihang_jiangxi','CN','CN-JX','南昌市','北航江西研究院航空与数字技术转化|Beihang Jiangxi aviation and digital technology transfer',
 'intermediary','manufacturing','https://kjj.nc.gov.cn/nckjj/kjjdt/202308/21fc1ae0a94c49598ddc92c955c15b24.shtml','南昌市科学技术局','zh',
 '研究院依托北航，围绕江西航空和电子信息产业配置研发及成果转化能力。|The institute draws on Beihang to support R&D and transfer for Jiangxi aviation and electronics industries.',
 '北航江西研究院、北京航空航天大学和当地航空电子产业主体。|Beihang Jiangxi institute, Beihang University and local aviation/electronics organisations.',
 '将航空发动机、智能制造、人工智能与工业物联网、培训配置为四块业务。|Four business areas connect aero-engines, intelligent manufacturing, AI/industrial IoT and training.',
 '2023年科技局报道明确四类业务和新型研发机构身份。|A 2023 science-authority account identifies the four areas and new R&D-institution status.',
 '研究布局不自动形成企业订单与型号应用。|Research domains do not by themselves establish orders or deployment.',
 '围绕地方制造环节制定工程交付清单，避免仅迁移高校课题。|Define engineering deliverables around local production, rather than relocating academic topics.')
add('ganjiang_engineering','CN','CN-JX','赣州市','赣江创新研究院稀土工程试验平台|Ganjiang rare-earth engineering research platform',
 'mission','materials','https://www.cas.cn/yw/202404/t20240412_5011421.shtml','中国科学院','zh',
 '赣江创新院把稀土研究、材料化学、资源环境与工程试验能力集中配置，服务稀土关键技术任务。|Ganjiang integrates rare-earth science, materials chemistry, resources/environment and engineering trials for critical technology tasks.',
 '中国科学院赣江创新研究院、院地合作方和稀土产业技术用户。|Ganjiang Institute, regional partners and rare-earth technology users.',
 '建制化组织基础研究和工程试验，按国家与产业需求凝练研究任务。|Institutional research and engineering trials are organised around national and industrial needs.',
 '2024年科学院记录确认工程试验中心和三类研究平台的现场调研。|A 2024 CAS account documents the engineering trial centre and three research platforms.',
 '平台存在不等于全部稀土工艺均已工业验证。|Facilities do not establish industrial validation of every rare-earth process.',
 '把关键材料任务分解为可复现试验及企业联合验证。|Translate materials tasks into repeatable trials and joint industrial validation.',factors=('knowledge','infrastructure','market'))
add('yazhou_seed','CN','CN-HI','三亚市','崖州湾南繁种业成果转化生态|Yazhou Bay Nanfan seed technology-transfer ecosystem',
 'cluster','biomanufacturing','https://agri.hainan.gov.cn/hnsnyt/ywdt/zwdt/202502/t20250226_3822685.html','海南省农业农村厅','zh',
 '科技城把种业企业、高校研究院与育种设施集聚，通过先投后股支持南繁成果转化。|The science city co-locates seed firms, university institutes and breeding facilities, with grant-to-equity support for transfer.',
 '崖州湾科技城、中种集团、国投种业、科研院所与高校研究院。|Yazhou Bay science city, China Seed, SDIC Seed, research institutes and university institutes.',
 '共享育种科研条件与专业化资金运作连接技术合同和企业落地。|Shared breeding infrastructure and professionally managed finance connect technology contracts to industrial implementation.',
 '2025年官方报道列明企业与院所集聚及2024年试行的先投后股安排。|A 2025 official account documents co-location and the grant-to-equity arrangement introduced in 2024.',
 '生物安全、品种权与不同生态区试验制约品种推广。|Biosafety, variety rights and agroecological trials constrain diffusion.',
 '将品种验证、知识产权和试验地条件一并纳入转化合同。|Include variety tests, IP and trial-location conditions in transfer contracts.',factors=('knowledge','infrastructure','capital','market'),institutions=('research','ip'))
add('guizhou_pesticide','CN','CN-GZ','贵阳市','贵州大学与海利尔绿色农药联合研发|Guizhou University–Hailir green-pesticide joint R&D',
 'consortium','biomanufacturing','https://www.gzu.edu.cn/_t2805/2026/0913/c17516a279393/page.htm','贵州大学','zh',
 '大学与农药企业签订合作协议，拟共建联合实验室并推进绿色农药定向转化。|A university and pesticide firm agree to establish a joint laboratory and pursue targeted green-pesticide transfer.',
 '贵州大学、绿色农药全国重点实验室、海利尔药业集团。|Guizhou University, its green-pesticide laboratory and Hailir Pesticides and Chemicals Group.',
 '总体协议后逐项落实研发任务，强调田间试验和安全评价。|An overarching agreement is to be followed by individual R&D tasks, field trials and safety assessment.',
 '2026年9月13日校方报道确认前一日签署战略合作协议。|A university account dated 13 September 2026 confirms the agreement signed the previous day.',
 '签约不证明新农药已经登记或商业应用。|An agreement does not establish registration or commercial use of a new pesticide.',
 '让研发、田间验证和登记责任在联合体内清晰分工。|Allocate research, field testing and registration responsibilities clearly within the consortium.')
add('guizhou_aluminium','CN','CN-GZ','贵阳市','贵州铝产业工程技术创新中心|Guizhou aluminium engineering innovation centre',
 'consortium','materials','https://www.gzu.edu.cn/2025/0311/c17516a246211/page.htm','贵州大学','zh',
 '贵州大学与成黔集团共同建立工程技术中心，围绕铝土矿开发与综合利用组织研究。|Guizhou University and Chengqian Group jointly establish an engineering centre for bauxite development and utilisation.',
 '贵州大学、贵州成黔集团及矿业工程研究团队。|Guizhou University, Chengqian Group and mining engineering researchers.',
 '大学工程团队与资源企业共建中心，连接研究方向和矿产应用问题。|University engineers and a resource firm co-establish a centre linking research to mineral applications.',
 '2025年3月校方记录确认中心揭牌及资源开发、综合利用研究方向。|A March 2025 university account confirms launch and research in resource development/utilisation.',
 '成立中心不代表已有商业化工艺。|Centre establishment is not evidence of a commercial process.',
 '以原料适配、回收率和环境指标约束联合研究任务。|Define joint tasks through feedstock compatibility, recovery and environmental measures.')
add('tibet_yak','CN','CN-XZ','拉萨市','西藏牦牛育种政产学研合作群|Tibet yak-breeding research–industry collaboration',
 'consortium','biomanufacturing','https://sti.xizang.gov.cn/xwzx/qnkjdt/202508/t20250814_495308.html','西藏自治区科学技术厅','zh',
 '高原生物研究团队围绕全基因组选择与体细胞克隆，联结地方育种基地、高校和畜牧服务机构。|Plateau biologists connect genomic selection and cloning research with local breeding bases, universities and livestock services.',
 '西藏自治区高原生物所、合作科研团队、当雄等地方主体、西藏大学和畜牧总站。|Tibet Plateau Biology Institute, research partners, Damxung/local actors, Tibet University and livestock services.',
 '以具体育种技术任务形成一加多合作群，连接研究、繁育与产业服务。|A core-plus-partners arrangement links a defined breeding task to reproduction and industrial services.',
 '2025年官方记录提供克隆牦牛诞生时间线；种质库与转化生产线为后续规划。|The 2025 official record provides a cloned-yak timeline; germplasm infrastructure and production lines are future plans.',
 '单次克隆成功不证明群体增产、生态收益或成本可行。|A successful clone does not establish herd productivity, ecological benefit or economic viability.',
 '持续核验繁育健康、遗传多样性与牧户使用成本。|Follow breeding health, genetic diversity and costs to pastoral users.')
add('ningdong_pilot','CN','CN-NX','银川市','宁东现代煤化工中试基地|Ningdong modern coal-chemical pilot base',
 'pilot','materials','https://dofcom.nx.gov.cn/tznx/tzgk/zszc/202207/t20220728_3638439.html','宁夏回族自治区商务厅','zh',
 '基地向院所和企业提供化工中试熟化载体，支持煤基材料、精细化工、氢能与循环利用研发。|The base hosts chemical piloting for institutes and firms in coal-derived materials, fine chemicals, hydrogen and circular processes.',
 '宁东管委会、宁东科创公司、入驻研发机构、高校与企业。|Ningdong authority, its innovation operator, resident research institutes, universities and firms.',
 '通过驻地研发机构及联合设立机构提供研发、中试、工业试验、检测和市场服务。|Resident and jointly established institutes offer R&D, piloting, industrial trials, testing and market services.',
 '官方支持政策列明机构准入退出与共性服务范围；资助条款不作为实施成果。|Official rules specify entry/exit and shared services; funding provisions are not treated as achieved results.',
 '化工安全与煤基路径排放须独立核验，不能由技术转化推断低碳。|Chemical safety and coal-pathway emissions need independent assessment; transfer is not proof of decarbonisation.',
 '在中试验收中分别记录质量、连续运行、安全和全流程能耗。|Record quality, continuous operation, safety and process-wide energy use at pilot acceptance.',factors=('knowledge','infrastructure','market'))
add('xinjiang_medicine','CN','CN-XJ','乌鲁木齐市','新疆民族药公共中试与质量平台|Xinjiang ethnic-medicine pilot and quality platform',
 'pilot','biomanufacturing','https://www.xjipc.cas.cn/zzjgnew/zcpt2022/ywzs/','中国科学院新疆理化技术研究所','zh',
 '药物中试中心把公共检测、天然植物提取和口服制剂中试配置在同一平台，服务民族药企业。|The centre combines public testing, plant extraction and oral-formulation pilots for ethnic-medicine firms.',
 '新疆理化技术研究所、药物中试技术中心、生物医药企业与中亚合作方。|Xinjiang Technical Institute of Physics and Chemistry, its pilot centre, biopharma firms and Central Asian partners.',
 '以共性技术、质量分析和制剂放大连接科研与企业研发，并开展国际技术合作。|Shared technologies, quality analysis and formulation scale-up link research to firms and international collaboration.',
 '官网列明三个组成平台及CMA检测资质，不将其拆成三个案例。|The official page identifies three components and CMA testing qualification, counted as one platform.',
 '检测资质和中试能力不能代替药品上市许可。|Testing qualification and pilot capacity do not replace medicine approval.',
 '把质量标准、工艺可复现性和监管路径作为转化前置条件。|Make quality standards, repeatable processes and regulatory pathways prerequisites for transfer.',factors=('knowledge','infrastructure','market'),institutions=('research','standards'))
add('yunnan_boton','CN','CN-YN','昆明市','云南波顿香精香料协同研究院|Yunnan Boton flavour and fragrance collaborative institute',
 'consortium','biomanufacturing','https://www.kib.cas.cn/gkjj/yjsnb/201906/P020190605383130978267.pdf','中国科学院昆明植物研究所','zh',
 '昆明植物所、云南省科学技术院和波顿集团共同设立研究院，围绕天然香料资源开展产学研用合作。|Kunming Institute of Botany, Yunnan Academy of Science and Boton jointly create an institute around natural fragrance resources.',
 '昆明植物研究所、云南省科学技术院、波顿集团。|Kunming Institute of Botany, Yunnan Academy of Science and Boton Group.',
 '地方植物资源、科研能力与企业加工及市场接口由共建研究院衔接。|A joint institute connects botanical resources and research with industrial processing and markets.',
 '2019年所年报记载2018年在昆明成立研究院；面向南亚东南亚是平台方向。|The 2019 institute report records establishment in Kunming in 2018; South/Southeast Asian outreach is an intended direction.',
 '历史成立记录不证明目前产量或跨境市场份额。|Historical establishment does not establish present output or cross-border market share.',
 '围绕原料溯源、质量稳定性和企业试用组织联合研发。|Organise joint research around traceable feedstock, consistent quality and industrial trials.')
add('yunnan_material_genome','CN','CN-YN','昆明市','云南稀贵金属材料基因工程协同平台|Yunnan rare/precious-metal materials-genome collaboration',
 'consortium','materials','https://kjt.yn.gov.cn/html/2023/gongzuodongtai_0607/7290.html','云南省科学技术厅','zh',
 '材料基因工程以计算、制备表征和数据平台支持企业主导的材料研发与验证。|Materials-genome infrastructure supports enterprise-led materials R&D and validation through computation, characterisation and data.',
 '云南科技部门、材料企业、高校院所及材料研发平台。|Yunnan science authorities, materials firms, research institutes/universities and R&D platforms.',
 '政产学研用协同组织，推进材料数据共享及验证性应用，连接资源产业与数据驱动研发。|Government–industry–research coordination connects data sharing, application trials and resource industries.',
 '2023年科技厅绩效反馈确认一期平台和数据库已建成，二期应用为后续任务。|A 2023 authority review identifies completed first-phase platforms/databases and subsequent application tasks.',
 '数据库积累不自动缩短产业研发周期。|Data accumulation does not automatically shorten industrial development cycles.',
 '用同一材料的性能、试验周期和工艺复现检验共享数据价值。|Assess data value through material performance, trial duration and process reproducibility.',factors=('knowledge','data','infrastructure','market'),institutions=('research','data'))

add('jianghuai_medrobot','CN','CN-AH','合肥市','安徽医科大学医用机器人产教合作|Anhui medical-robotics education–industry partnership',
 'consortium','manufacturing','https://www.jhatc.cn/html/web/kexue/kycp/index.html','江淮前沿技术协同创新中心','zh',
 '临床大学、协同创新中心与机器人企业共同建立产业学院及医学智能设备公司。|A medical university, innovation centre and robotics firm establish an industry school and medical-device company.',
 '安徽医科大学、江淮前沿技术协同创新中心、北京天智航。|Anhui Medical University, Jianghuai collaborative innovation centre and Beijing Tinavi.',
 '把临床需求、工程研发、人才培养与企业承接配置在同一合作框架。|The partnership connects clinical demand, engineering, training and a commercial operator.',
 '官方成果转化栏目记录2026年3月15日揭牌。|The official transfer listing records the launch on 15 March 2026.',
 '公司成立不代表器械获准上市。|Company formation does not establish device approval.',
 '让临床验证和注册要求共同约束研发任务。|Use clinical validation and registration requirements to define R&D tasks.')
add('jiageng_lab','CN','CN-FJ','厦门市','嘉庚创新实验室材料转化平台|Jiageng Innovation Laboratory materials transfer',
 'pilot','materials','https://www.fujian.gov.cn/zwgk/ztzl/sxzygwzxsgzx/sdjj/szjj/202604/t20260413_7123544.htm','福建省人民政府','zh',
 '实验室以材料研发、公共技术服务和企业孵化衔接能源材料研究与工业应用。|The laboratory connects energy-materials research to industry through R&D, shared services and incubation.',
 '嘉庚创新实验室、材料与氢能研发团队及孵化企业。|Jiageng Innovation Laboratory, materials/hydrogen teams and incubated firms.',
 '自动化材料研究与公共服务设施支持技术验证，创业企业承接成果。|Automated materials research and shared facilities support validation, with spin-outs taking results forward.',
 '2026年省政府报道确认入选产业技术基础公共服务平台，并介绍氢能成果孵化。|A 2026 government account confirms selection as an industrial technology public-service platform and hydrogen incubation.',
 '入选平台不能证明所有技术已达到量产要求。|Platform recognition does not establish manufacturing readiness for every technology.',
 '对研发、工程放大和客户认证分别设置验收节点。|Separate research, scale-up and customer qualification milestones.',factors=('knowledge','infrastructure','market'))
add('qingyuan_lab','CN','CN-FJ','泉州市','清源创新实验室共建中试|Qingyuan Innovation Laboratory joint piloting',
 'pilot','materials','https://www.fujian.gov.cn/xwdt/fjyw/202603/t20260310_7107826.htm','福建省人民政府','zh',
 '清源实验室与材料及环保企业共建研发和中试设施，衔接化工研究与制造。|Qingyuan collaborates with materials and environmental firms on R&D and pilot facilities.',
 '清源创新实验室、福建纯铭材料、远致环保。|Qingyuan Innovation Laboratory, Fujian Chunming Materials and Yuanzhi Environmental Protection.',
 '共建平台、中试及人才合作将企业问题转为联合工程任务。|Shared platforms, piloting and talent collaboration turn industrial problems into joint engineering tasks.',
 '2026年官方报道列举材料中试平台和环保联合研发中心。|A 2026 official account identifies a materials pilot platform and environmental joint R&D centre.',
 '规划产值不是已经实现的产出。|Projected output is not realised production.',
 '用企业试用与连续工艺验证评价共建平台。|Evaluate joint platforms through industrial trials and continuous-process validation.',factors=('knowledge','infrastructure','market'))
add('mindu_lab','CN','CN-FJ','福州市','闽都创新实验室企业联合研发|Mindu Innovation Laboratory industry-led joint R&D',
 'consortium','digital','https://www.fujian.gov.cn/xwdt/fjyw/202603/t20260310_7107826.htm','福建省人民政府','zh',
 '闽都实验室以企业出题、实验室答题连接光电子芯片和光学材料研发。|Mindu uses company-defined problems to organise optoelectronic-chip and optical-materials research.',
 '闽都创新实验室、福建中科光芯及联合研发企业。|Mindu Innovation Laboratory, Fujian Zhongke Optical Chip and joint-research firms.',
 '企业联合中心将研究任务与产品需求、工艺验证相衔接。|Joint centres connect research tasks with product requirements and process validation.',
 '官方报道举出光电子芯片量产与透明荧光陶瓷成果。|The official account describes chip manufacturing and transparent fluorescent-ceramic results.',
 '具名成果不能外推为全部联合项目的成功率。|Named results do not establish success rates across all joint projects.',
 '以具体器件指标和客户验证来组织联合研发。|Organise collaboration around device specifications and customer validation.')
add('sichuan_lowcarbon_transport','CN','CN-SC','成都市','四川低碳交通研究中心|Sichuan low-carbon transport research centre',
 'consortium','industry','https://jtj.yaan.gov.cn/xinwen/show/ca0c0ea6d605dc5c0a3cb730ace4298d.html','雅安市交通运输局','zh',
 '交通科研机构联合工程、港口、车辆企业和高校，建设分布式低碳交通研究平台。|A transport institute joins engineering, port and vehicle firms and a university in distributed low-carbon transport R&D.',
 '四川省交科院、蜀道集团、港投集团、设计院、比亚迪、长沙理工大学。|Sichuan transport institute, Shudao, port operators, design institutes, BYD and Changsha University of Science and Technology.',
 '以一加六加多的合作网络覆盖交通建设和运营中的工程问题。|A core-and-partners network addresses engineering problems in transport construction and operation.',
 '官方报道确认中心挂牌入驻天府永兴实验室。|The official account confirms its launch within Tianfu Yongxing Laboratory.',
 '既有交通工程不能全部归因于新中心。|Existing transport projects cannot all be attributed to the new centre.',
 '由交通业主提供可测量的运营场景和减排边界。|Have asset operators define measurable operating scenarios and emissions boundaries.')
add('songshan_institute','CN','CN-HA','郑州市','嵩山实验室产业研究院|Songshan Laboratory industrial research institute',
 'mission','digital','https://public.zhengdong.gov.cn/D0605X/8582150.jhtml','郑东新区管理委员会','zh',
 '信息领域科研力量通过产业研究院公司组织联合研发与成果转化。|Information-technology research partners use an industrial-institute company for joint R&D and transfer.',
 '嵩山实验室产业研究院、信息工程大学、郑州大学、中国电科第二十七研究所。|Songshan industrial institute, Information Engineering University, Zhengzhou University and CETC 27th Institute.',
 '大学和专业研究机构共建公司，知识产权管理支撑产业合作。|Universities and a specialist institute jointly establish a company supported by IP management.',
 '政府知识产权工作记录确认研究院及其共建单位。|A government IP-work record identifies the institute and its founding partners.',
 '机构设立与知识产权服务不等于产品收入。|Institutional establishment and IP services are not product revenue.',
 '把科研任务、知识产权归属与企业使用条件同时明确。|Specify research tasks, IP ownership and industrial access together.',institutions=('research','ip'))
add('harbin_fusion','CN','CN-HL','哈尔滨市','哈尔滨聚变与超导产业技术创新联盟|Harbin fusion and superconductivity innovation alliance',
 'consortium','industry','https://www.most.gov.cn/dfkj/hlj/zxdt/202608/t20260820_197173.html','科学技术部','zh',
 '高校、科研院所和装备企业围绕聚变及超导组织跨地区产业技术联盟。|Universities, institutes and equipment firms form a cross-regional alliance in fusion and superconductivity.',
 '哈尔滨工业大学、哈尔滨工程大学、哈电集团、相关核科学研究机构及超导企业。|Harbin Institute of Technology, Harbin Engineering University, Harbin Electric, nuclear institutes and superconductivity firms.',
 '联盟拟通过联合攻关、平台共享与标准协作连接科学研究和装备工程。|The alliance plans joint research, shared platforms and standards collaboration linking science to equipment engineering.',
 '2026年8月官方信息确认联盟成立及具名成员。|An August 2026 official account confirms formation and named members.',
 '成立联盟不代表聚变发电已商业可用。|Alliance formation does not establish commercial fusion generation.',
 '围绕关键部件测试和供应链质量形成分阶段联合任务。|Stage joint tasks around component testing and supply-chain quality.',institutions=('research','standards'))
add('tju_distillation','CN','CN-TJ','天津市','天津大学精馏技术工程转化|Tianjin University distillation engineering transfer',
 'pilot','industry','https://www.tju.edu.cn/info/1059/77612.htm','天津大学','zh',
 '精馏工程中心连接过程研究、塔器装备及化工企业的工艺放大需求。|The distillation centre connects process research, column equipment and industrial scale-up.',
 '天津大学精馏技术国家工程研究中心、北洋工程公司及石化企业。|Tianjin University distillation centre, Beiyang engineering company and petrochemical firms.',
 '联合平台、工程设计和设备制造把分离技术送入工业过程。|Joint platforms, engineering design and equipment manufacture bring separation technologies into industrial processes.',
 '大学介绍列明工艺控制、诊断、模拟和产业合作能力。|The university profile documents control, diagnosis, simulation and industry collaboration capabilities.',
 '单一工况性能不能直接外推至不同原料及装置。|Performance under one operating condition cannot be generalised to other feedstocks or plants.',
 '以实际物料试验和运行能耗验证放大效果。|Validate scale-up using actual feedstocks and operating energy demand.',factors=('knowledge','infrastructure','market'))
add('qibebt_transfer','CN','CN-SD','青岛市','青岛能源所多路径技术转移|QIBEBT multi-path technology transfer',
 'intermediary','industry','https://qibebt.cas.cn/cgzh/gk/','中国科学院青岛生物能源与过程研究所','zh',
 '研究所通过联合项目、共建平台、许可及成果转让连接能源生物研究与企业。|The institute links bioenergy research to firms through joint projects, platforms, licensing and technology assignment.',
 '青岛能源所、国家能源集团、中石化、中石油、山东能源及生物产业企业。|QIBEBT, CHN Energy, Sinopec, CNPC, Shandong Energy and bioindustry firms.',
 '按技术和合作对象选择许可、转让或条件性股权转化，不用单一路径承接所有成果。|Licensing, assignment or conditional equity arrangements are chosen for the technology and partner.',
 '官方转化概况明确合作与知识产权路径，并列举企业伙伴。|The official transfer profile identifies cooperation/IP routes and industrial partners.',
 '合作机制不能替代具体项目的商业验证。|Cooperation mechanisms do not replace commercial validation.',
 '在签约前明确成熟度、转化责任及后续改进权。|Specify readiness, transfer responsibilities and improvement rights before contracting.',institutions=('research','ip'))
add('wuwei_heavyion','CN','CN-GS','武威市','武威重离子医疗工程转化|Wuwei heavy-ion medical engineering transfer',
 'intermediary','manufacturing','https://zwfw.gansu.gov.cn/wuwei/ztfw/zsyzfwzq/sztsqy/art/2023/art_4d3e1c3b25944a028e8ce3a8848c655e.html','甘肃政务服务网','zh',
 '加速器科研技术与专科医院应用衔接，形成重离子医疗装备的工程和临床接口。|Accelerator research is connected to specialist-hospital applications, linking engineering and clinical use.',
 '中国科学院近代物理研究所、武威重离子中心、甘肃省武威肿瘤医院。|Institute of Modern Physics, Wuwei heavy-ion centre and Gansu Wuwei tumour hospital.',
 '科研机构提供装备技术，医疗机构承接应用与临床运行。|A research institute supplies equipment technology while a hospital hosts clinical operation.',
 '官方介绍列明技术来源、装备和医院应用主体。|The official profile identifies technology provenance, equipment and the hospital operator.',
 '设施运行不等于所有适应症均有相同疗效。|Facility operation does not establish equal efficacy across indications.',
 '同步设置装备可靠性、临床证据和运维能力门槛。|Set requirements for equipment reliability, clinical evidence and maintenance.')
add('changli_metals','CN','CN-HE','秦皇岛市','燕山大学昌黎金属材料绿色智造研究院|Yanshan–Changli green intelligent metals institute',
 'cluster','materials','https://cri.ysu.edu.cn/gywm/yjyjj.htm','燕山大学','zh',
 '大学与昌黎县共建研究院，面向当地金属材料和制造企业组织联合研发及中试。|Yanshan University and Changli County co-establish an institute for metals/manufacturing R&D and piloting.',
 '燕山大学、昌黎县及金属材料、装备和冶金企业。|Yanshan University, Changli County and metals, equipment and metallurgy firms.',
 '企业提出问题，研究团队组织研发，地方政府支持共享设施与人才合作。|Companies define problems, researchers organise R&D and local government supports facilities and talent cooperation.',
 '研究院简介列明共建主体、五类技术方向与联合实验室安排。|The profile names founders, five technical areas and joint-laboratory arrangements.',
 '订单协作模式不证明各企业已经实现网络化制造。|The collaboration model does not establish networked manufacturing at every firm.',
 '以企业工艺问题和中试交付形成可复核的共同任务。|Build auditable joint tasks around industrial process problems and pilot deliverables.',factors=('knowledge','infrastructure','market'))
add('qinhuangdao_rehab','CN','CN-HE','秦皇岛市','秦皇岛康复器具产学研合作|Qinhuangdao rehabilitation-device collaboration',
 'consortium','manufacturing','https://www.ysu.edu.cn/news/info/5502/15687.htm','燕山大学','zh',
 '工程团队、医院和康养企业联合申报智能康复器具与诊疗装备任务。|Engineering teams, hospitals and a care company jointly pursue intelligent rehabilitation and diagnostic devices.',
 '燕山大学、康复辅具研究机构秦皇岛研究院、当地医院和中秦兴龙康养。|Yanshan University, a Qinhuangdao rehabilitation institute, local hospitals and Zhongqin Xinglong care company.',
 '临床问题、工程研发与应用主体通过揭榜项目对接。|Challenge-based projects connect clinical problems, engineering and application partners.',
 '校方信息确认相关团队项目入围，未将入围视作获批产品。|The university records project shortlisting, not product approval.',
 '入围项目不能证明器械安全性与临床效果。|Shortlisting does not establish device safety or clinical efficacy.',
 '让医院参与需求定义及后续试验设计。|Include hospitals in requirements and subsequent trial design.')
add('digital_design_centre','CN','CN-HB','武汉市','国家数字化设计与制造创新中心|National digital design and manufacturing innovation centre',
 'consortium','digital','https://cctt.hust.edu.cn/info/1041/1726.htm','华中科技大学','zh',
 '高校和制造企业以公司、联盟及网络共同组织数字设计与制造技术研发。|Universities and manufacturers organise digital design/manufacturing R&D through a company, alliance and network.',
 '华中科技大学、清华大学及相关高校、中国一汽等制造主体。|HUST, Tsinghua and other universities, FAW and manufacturing partners.',
 '公司承担运营，联盟汇集需求和研发伙伴，网络支撑行业技术扩散。|A company operates the platform, an alliance pools demand and partners, and a network supports diffusion.',
 '官方介绍记录2018年获批及联盟组织形式。|The official profile records 2018 approval and the alliance structure.',
 '研发平台成立不证明工业软件已被所有成员采用。|Platform formation does not establish industrial-software adoption by all members.',
 '用兼容性测试与真实产线应用评价共性软件。|Evaluate shared software through interoperability tests and production-line use.',factors=('knowledge','data','market'),institutions=('research','standards'))
add('digital_construction_centre','CN','CN-HB','武汉市','国家数字建造技术创新中心|National digital construction technology innovation centre',
 'mission','manufacturing','https://civil.hust.edu.cn/syzx1/gjszjzjscxzx.htm','华中科技大学土木与水利工程学院','zh',
 '中心围绕数字建造组织物联网、机器人、城市信息模型和工程应用平台。|The centre organises IoT, robotics, city information modelling and engineering applications for digital construction.',
 '华中科技大学、建筑工程企业及合作科研金融机构。|HUST, construction companies and research/finance partners.',
 '一加多平台把共性技术研究与建筑、桥梁和轨道工程场景连接。|A core-and-platforms structure links shared research to buildings, bridges and rail engineering.',
 '官方介绍确认2022年获批及技术平台、工程应用布局。|The official profile records 2022 approval and the technical/application platform structure.',
 '工程场景差异限制直接复制同一技术方案。|Different engineering settings limit direct replication.',
 '按设计、施工和运维环节分别验证数字技术价值。|Verify digital technologies separately in design, construction and operation.',factors=('knowledge','data','infrastructure','market'))
add('xiangjiang_energy','CN','CN-HN','长沙市','湘江实验室与湖南能源集团联合研发|Xiangjiang Laboratory–Hunan Energy joint R&D',
 'consortium','digital','https://gzw.hunan.gov.cn/gzjg/gqdt/202406/t20240605_33320191.html','湖南省国资委','zh',
 '能源集团与实验室签订合作框架，将算力和人工智能研究对接电力、天然气场景。|An energy group and laboratory agree to connect computing/AI research with power and natural-gas applications.',
 '湖南能源集团、湘江实验室、湖南工商大学。|Hunan Energy Group, Xiangjiang Laboratory and Hunan University of Technology and Business.',
 '以企业数据和应用场景支撑联合研究、成果转化及示范安排。|Corporate data and applications support planned joint research, transfer and demonstrations.',
 '2024年官方报道确认战略协议签署及合作领域。|A 2024 official account confirms the agreement and its fields of cooperation.',
 '框架协议不能证明算法已投入生产。|A framework agreement does not establish production deployment.',
 '先明确数据授权、基线和现场验证责任。|Define data permissions, baselines and field-validation responsibilities first.',factors=('knowledge','data','market'),institutions=('research','data'))

# African institutions are independent operators, not branches of one network.
add('bitri','BW',None,None,'博茨瓦纳技术研究与创新研究所|Botswana Institute for Technology Research and Innovation',
 'intermediary','materials','https://bitri.co.bw/about-us/','BITRI','en',
 '研究所围绕本地产业需求开展应用研究，提供材料分析和技术开发能力。|BITRI undertakes needs-driven applied research and provides materials analysis and technology development.',
 'BITRI、企业、公共部门及社区伙伴。|BITRI, businesses, public bodies and community partners.',
 '专业实验设施与联合研发连接本地资源、工程问题和企业需求。|Specialist facilities and collaborative R&D connect local resources, engineering problems and industrial demand.',
 '官方简介列出能源、材料及数字技术研究与合作职责。|The official profile identifies energy, materials and digital research and collaboration functions.',
 '研究职能不是企业采用或商业收入的证明。|Research functions do not establish adoption or commercial revenue.',
 '优先围绕企业可验证的质量和加工瓶颈开展合作。|Prioritise verifiable industrial quality and processing bottlenecks.',factors=('knowledge','infrastructure','market'))
add('kirdi','KE',None,None,'肯尼亚工业研究与发展研究所|Kenya Industrial Research and Development Institute',
 'intermediary','manufacturing','https://kirdi.go.ke/homepage','KIRDI','en',
 '工业研究所向企业提供食品、纺织、皮革、陶瓷及能源等领域的应用研发与共用设施。|KIRDI offers applied research and shared facilities in food, textiles, leather, ceramics and energy.',
 'KIRDI、制造企业和中小企业。|KIRDI, manufacturers and SMEs.',
 '研发、测试及共享生产设施支持企业改进工艺和产品。|Research, testing and common manufacturing facilities support process and product improvements.',
 '官网列示技术服务及共用制造设施。|The official site lists technical services and common manufacturing facilities.',
 '设施可用不代表所有企业都有能力持续使用。|Facility availability does not establish firms’ sustained capacity to use it.',
 '把操作培训、质量测试和企业后续维护一并纳入服务。|Combine operator training, quality tests and ongoing maintenance support.',factors=('knowledge','infrastructure','talent'))
add('nirda_opencalls','RW',None,None,'卢旺达工业研发署企业技术升级计划|NIRDA industrial technology-upgrading programme',
 'capacity','manufacturing','https://www.nirda.gov.rw/updates/news-details/nirdas-open-calls-program-empowers-firms-in-eight-value-chains-with-upgraded-equipment-1','NIRDA','en',
 '公开征集计划向不同价值链企业提供设备升级和配套技术支持。|An open-call programme supplies equipment upgrades and complementary technical support to firms across value chains.',
 '卢旺达工业研发署、入选企业和技术服务伙伴。|NIRDA, selected firms and technical-service partners.',
 '公开遴选后将技术获取、企业能力和商业辅导结合。|Selection links technology acquisition with firm capabilities and business support.',
 '2023年官方报道记录八类价值链企业获得升级设备。|A 2023 official account records upgraded equipment for firms in eight value chains.',
 '设备交付不等于生产率已持续提高。|Equipment delivery is not sustained productivity improvement.',
 '以设备使用率、操作能力和产品质量核验升级成效。|Verify upgrading through utilisation, operator competence and product quality.',factors=('infrastructure','talent','market'))
add('uiri','UG',None,None,'乌干达工业研究所中试与企业服务|Uganda Industrial Research Institute piloting and enterprise services',
 'intermediary','manufacturing','https://www.uiri.go.ug/faqs','UIRI','en',
 '研究所将产品配方、分析测试、机械设计和中试加工能力向企业开放。|UIRI offers firms formulation, analytical testing, machinery design and pilot processing.',
 '乌干达工业研究所、工业企业及创业团队。|UIRI, industrial firms and entrepreneurs.',
 '试制、工程制造与孵化服务降低小企业获取研发设备的门槛。|Prototyping, fabrication and incubation lower barriers to R&D equipment for smaller firms.',
 '官方服务说明列明中试、测试及企业培育职能。|The official service description identifies piloting, testing and incubation.',
 '孵化支持不能替代市场订单与稳定供应链。|Incubation cannot substitute for orders and reliable supply chains.',
 '让试制批次与客户质量要求相衔接。|Align pilot batches with customer quality requirements.',factors=('knowledge','infrastructure','market'))
add('tirdo_pilot','TZ',None,None,'坦桑尼亚工业研发组织技术转移与中试|TIRDO technology transfer and pilot plants',
 'pilot','manufacturing','https://www.tirdo.or.tz/en/technology','TIRDO','en',
 '技术转移部门管理研发成果、商业潜力评估和中试设施。|The technology-transfer division manages research outputs, commercial-potential assessment and pilot facilities.',
 '坦桑尼亚工业研发组织、研发人员和产业用户。|TIRDO, researchers and industrial users.',
 '技术盘点、知识产权与许可工作将研究成果接入工程验证和市场。|Technology inventories, IP and licensing connect research to engineering validation and markets.',
 '官方部门页面明确技术转移及中试职责。|The official division page specifies transfer and pilot-plant responsibilities.',
 '职责说明没有提供项目级商业成功率。|The mandate does not provide project-level commercial success rates.',
 '围绕可交付工艺和企业吸收能力选择中试项目。|Select pilots around deliverable processes and firms’ absorptive capacity.',factors=('knowledge','infrastructure','market'),institutions=('research','ip'))
add('naseni_commercialisation','NG',None,None,'尼日利亚科研成果商业化计划|NASENI research commercialisation programme',
 'capacity','general','https://nrcgp.naseni.gov.ng/','NASENI','en',
 '计划征集已有科研成果，为商业化研发和技术应用提供项目遴选渠道。|The programme solicits research results for selection into commercialisation and technology-application support.',
 '尼日利亚国家科学与工程基础设施署、研究人员及项目合作方。|NASENI, researchers and project partners.',
 '以申请、知识产权声明和评审衔接研究成果与商业化支持。|Applications, IP declarations and review connect research results with commercialisation support.',
 '官方门户公开申请规则与成果原创性要求。|The official portal publishes application rules and originality requirements.',
 '开放申请不代表项目已经获得资助或投产。|An open application does not establish funding awards or production.',
 '将技术验证与企业承接方案作为评审的独立内容。|Review validation evidence and the industrial uptake plan separately.',institutions=('research','ip'))
add('proda','NG',None,None,'尼日利亚产品开发研究所工程转化|PRODA industrial engineering and product development',
 'intermediary','manufacturing','https://proda.gov.ng/','PRODA','en',
 '研究所围绕农业加工、陶瓷、化工及能源需求开展产品和工程研发。|PRODA develops products and engineering solutions for agro-processing, ceramics, chemicals and energy.',
 '产品开发研究所、工业合作伙伴及技术用户。|PRODA, industrial partners and technology users.',
 '需求导向研究与原型工程把实验室成果推进至可制造方案。|Demand-led research and prototype engineering move laboratory results towards manufacturable designs.',
 '官网列明研究方向及产业合作职能。|The official site identifies research areas and industry collaboration functions.',
 '原型开发不等于具备成本竞争力的规模制造。|Prototypes do not establish cost-competitive manufacturing at scale.',
 '以本地零部件供应与维护条件约束工程设计。|Design around local component supply and maintenance conditions.')
add('fiiro','NG',None,None,'尼日利亚联邦工业研究所工艺中试|FIIRO industrial process piloting',
 'pilot','biomanufacturing','https://www.fiiro.gov.ng/index.php/about/welcome-to-fiiro','FIIRO','en',
 '联邦工业研究所通过食品等工业工艺开发和中试支持本地企业。|FIIRO supports local firms through industrial process development and piloting, including food processing.',
 '联邦工业研究所、加工企业和创业者。|FIIRO, processing firms and entrepreneurs.',
 '实验室研究、工艺放大及技术培训连接原料加工与产业应用。|Laboratory research, scale-up and training connect feedstock processing with industrial use.',
 '官方介绍明确工业研发、技术适配与转移职责。|The official profile specifies industrial R&D, adaptation and transfer responsibilities.',
 '工艺转移仍取决于原料稳定性和质量控制。|Transfer depends on feedstock consistency and quality control.',
 '在企业试用前检验加工质量、能耗及设备可维护性。|Check product quality, energy use and maintainability before industrial trials.',factors=('knowledge','infrastructure','talent'))
add('mintek_transfer','ZA',None,None,'南非矿物技术研究院技术转移|Mintek minerals technology transfer',
 'intermediary','materials','https://mintek.co.za/collaborate/technology-transfer.html','Mintek','en',
 '技术转移办公室把矿物加工研究与客户需求、许可及商业合作连接。|Mintek’s transfer office connects mineral-processing research with customers, licensing and commercial collaboration.',
 'Mintek、矿业客户、许可企业及合资伙伴。|Mintek, mining customers, licensees and venture partners.',
 '后期研发适配客户工况，结合知识产权管理、许可和企业合作。|Late-stage R&D adapts to customer conditions, supported by IP management, licensing and partnerships.',
 '官方转移页面列明许可、产品销售及合资等路径。|The official transfer page identifies licensing, product sales and joint-venture routes.',
 '不同矿石及工况需要重新验证。|Different ores and operating conditions require renewed validation.',
 '把真实矿样和连续运行要求纳入转化合同。|Include actual ore samples and continuous-operation requirements in transfer contracts.',institutions=('research','ip'))
add('csir_iir','GH',None,None,'加纳工业研究所工程服务|Ghana CSIR industrial research services',
 'intermediary','manufacturing','https://iir.csir.org.gh/','CSIR–Institute of Industrial Research','en',
 '工业研究所依托仪器、加工及工程设施向企业提供应用研究和技术服务。|The institute uses instrumentation, machining and engineering facilities for applied research and industrial services.',
 '加纳科学与工业研究理事会工业研究所及企业。|Ghana CSIR’s Institute of Industrial Research and firms.',
 '共享工程能力使企业可获取专业研发、加工及测试支持。|Shared engineering capacity gives firms access to specialist R&D, fabrication and testing.',
 '官网展示研究方向及铸造、数控等工程服务设施。|The official site presents research areas and foundry/CNC engineering facilities.',
 '设备清单不能证明企业实际使用频率。|An equipment list does not establish industrial utilisation.',
 '以企业问题、交付质量和维护能力组织服务。|Organise services around industrial problems, deliverable quality and maintenance capacity.',factors=('knowledge','infrastructure','market'))
add('nghri','NA',None,None,'纳米比亚绿色氢能研究院|Namibia Green Hydrogen Research Institute',
 'consortium','industry','https://www.unam.edu.na/nghri','University of Namibia','en',
 '大学研究院以绿色氢能应用研究、人才培养及项目合作支撑新产业建设。|A university institute supports green hydrogen through applied research, training and project partnerships.',
 '纳米比亚大学、氢能企业、国际高校及项目开发方。|University of Namibia, hydrogen firms, international universities and developers.',
 '以大学、企业及政府合作连接人才、研究与示范项目。|University–industry–government collaboration links skills, research and demonstration projects.',
 '官网列举Daures和Walvis Bay等合作及2024年加氢设施进展。|The official page identifies Daures/Walvis Bay partnerships and a 2024 refuelling-facility milestone.',
 '示范设施不能证明全产业链已达到商业盈利。|Demonstrations do not establish profitability across the value chain.',
 '同步验证技术、当地技能形成和长期购买需求。|Assess technology, local skill formation and sustained offtake together.',factors=('knowledge','talent','market'))
add('ita_senegal','SN',None,None,'塞内加尔食品技术研究所中试|Senegal food technology institute piloting',
 'pilot','biomanufacturing','https://ita.sn/','Institut de Technologie Alimentaire','fr',
 '食品技术研究所通过实验室、加工中试和培训支持本地食品企业。|ITA supports local food businesses through laboratories, processing pilots and training.',
 '塞内加尔食品技术研究所、食品加工企业及技术学员。|Senegal’s ITA, food processors and technical trainees.',
 '谷物、水果、鱼类及乳品工艺与质量检测共同服务产品开发。|Cereal, fruit, fish and dairy processing and quality tests jointly support product development.',
 '官网列明中试车间、培训及食品分析实验室。|The official site lists pilot workshops, training and food-analysis laboratories.',
 '实验室合格不等于持续满足出口市场要求。|Laboratory conformity does not establish sustained compliance in export markets.',
 '把食品安全、保质期和工艺复现作为企业试用条件。|Require food safety, shelf life and process reproducibility in industrial trials.',factors=('knowledge','infrastructure','talent'))
add('i2t_drone','CI',None,None,'科特迪瓦I2T农业无人机技术合作|Côte d’Ivoire I2T agricultural drone partnership',
 'capacity','digital','https://i2t.ci/','I2T','fr',
 '技术研究机构与企业合作，推进农业无人机操作、喷洒和航空测绘培训。|A technology institute partners with a company on agricultural drone operation, spraying and aerial-mapping training.',
 'I2T、SCB SYSTEMS AFRICA及农业技术用户。|I2T, SCB SYSTEMS AFRICA and agricultural technology users.',
 '研究机构与技术企业联合提供应用技能和场景适配支持。|An institute and technology firm combine application skills with contextual adaptation.',
 '官网记录2026年7月22日合作协议及培训领域。|The official site records the 22 July 2026 agreement and training fields.',
 '协议不证明农户采用规模或作物增产。|The agreement does not establish farmer adoption or yield gains.',
 '以操作安全、农药规范和小农户成本核验应用条件。|Assess operating safety, pesticide rules and smallholder costs.',factors=('knowledge','talent','market'))

add('ytec','AR',None,None,'阿根廷Y-TEC能源联合研发公司|Argentina Y-TEC joint energy research company',
 'consortium','industry','https://www.conicet.gov.ar/ytec/sobre-y-tec/','CONICET','es',
 '能源企业与公共研究机构共同设立研发公司，将能源科学与企业工程问题结合。|An energy company and public research council establish a joint R&D company linking energy science to industrial engineering.',
 'YPF、阿根廷国家科学与技术研究委员会、Y-TEC研究团队。|YPF, CONICET and Y-TEC researchers.',
 '企业与科研机构共同持有研发载体，配置实验室、人才和行业合作。|Corporate and research partners co-own an R&D operator combining laboratories, skills and industry collaboration.',
 'CONICET介绍记录YPF与CONICET的共同设立及研发服务。|CONICET’s profile documents joint establishment and R&D services.',
 '设立时股权结构不等于已核验当前全部治理安排。|Founding ownership does not establish every present governance arrangement.',
 '明确长期共性研究与股东专有工程任务的资源边界。|Separate long-term shared research from shareholder-specific engineering tasks.')
add('amtc','CL',None,None,'智利先进矿业技术中心|Chile Advanced Mining Technology Center',
 'intermediary','materials','https://www.amtc.cl/colaboracion/que-ofrecemos/','AMTC','es',
 '矿业研究中心向行业提供协作研发、技术合同及实验室测试服务。|AMTC offers collaborative R&D, technology contracts and laboratory testing to mining.',
 '智利大学矿业研究团队、矿业企业和技术用户。|University of Chile mining researchers, mining firms and technology users.',
 '与企业共同定义技术任务，并通过合同研发和许可承接成果。|Industry co-defines technical tasks, with contract research and licensing supporting transfer.',
 '官方合作页面列明研发、测试和技术转移服务。|The official collaboration page identifies R&D, testing and transfer services.',
 '合同服务能力不证明所有矿场条件下均可部署。|Contract capability does not establish deployability under all mine conditions.',
 '将矿场数据、现场验证和技术责任纳入合同。|Include mine data, field validation and technical responsibilities in contracts.',institutions=('research','ip'))
add('ipt_brazil','BR',None,None,'巴西圣保罗技术研究院共享工程服务|Brazil IPT shared engineering services',
 'intermediary','manufacturing','https://ipt.br/solucoes-tecnologicas/','IPT','pt',
 '技术研究院向企业提供研发、测试、技术评价与多用户工程设施。|IPT offers firms R&D, testing, technical assessment and multi-user engineering facilities.',
 '圣保罗技术研究院、制造企业及公共技术用户。|IPT, manufacturers and public-sector technology users.',
 '多学科实验与工程服务把复杂产业问题转为可测试方案。|Multidisciplinary laboratory and engineering services turn industrial problems into testable solutions.',
 '官方技术服务目录明确研发、测试和共享设备能力。|The official service catalogue identifies R&D, testing and shared equipment.',
 '测试服务与技术创造应分别识别。|Testing services should be distinguished from technology creation.',
 '按客户问题组合研发、试验及独立评价。|Combine R&D, experiments and independent assessment around customer problems.',factors=('knowledge','infrastructure','market'))
add('fundacion_chile','CL',None,None,'智利基金会技术示范与产业培育|Fundación Chile technology demonstration and industry development',
 'intermediary','general','https://fch.cl/nosotros/sobre-nosotros/','Fundación Chile','es',
 '基金会通过引进和适配技术、示范企业及伙伴平台培育新产业。|The foundation develops industries through technology adaptation, demonstration businesses and partner platforms.',
 '智利基金会、技术伙伴、企业及公共机构。|Fundación Chile, technology partners, companies and public institutions.',
 '从示范企业到战略联盟，将技术机会与本地创业和产业能力结合。|Demonstration businesses and strategic alliances connect technology opportunities with local entrepreneurial capacity.',
 '官方历史介绍呈现企业示范向联盟和平台合作演进。|The official history describes an evolution from demonstration firms to alliances and platforms.',
 '历史成功经验受行业和市场条件限制。|Historical experience is conditional on sector and market context.',
 '先验证需求与本地配套，再选择投资或联盟路径。|Validate demand and local complements before choosing investment or alliance routes.')
add('agrosavia','CO',None,None,'哥伦比亚农业研究与区域创新网络|Colombia AGROSAVIA regional agricultural innovation',
 'capacity','biomanufacturing','https://www.agrosavia.co/','AGROSAVIA','es',
 '农业研究机构通过区域合作网络，将研究和技术转移对接不同规模生产者。|AGROSAVIA connects research and transfer to producers of different scales through regional networks.',
 'AGROSAVIA、农业生产者、企业和区域创新伙伴。|AGROSAVIA, producers, firms and regional innovation partners.',
 '以作物和畜牧价值链组织研究、推广与共同验证。|Crop and livestock value chains organise research, extension and joint validation.',
 '官网列示农业研究、技术转移及区域合作安排。|The official site identifies agricultural research, transfer and regional cooperation.',
 '同一技术对小农户与大型企业的成本约束不同。|A technology faces different cost constraints among smallholders and large firms.',
 '以区域试验和生产者反馈改进技术适配。|Use regional trials and producer feedback to improve adaptation.',factors=('knowledge','talent','market'))
add('espol_i3lab','EC',None,None,'厄瓜多尔ESPOL创新创业实验室|Ecuador ESPOL i3lab innovation and entrepreneurship',
 'venture','general','https://www.i3lab.org/','ESPOL i3lab','es',
 '大学创新中心把技术转移、创业支持与企业创新服务结合。|A university innovation centre combines transfer, entrepreneurship support and corporate innovation.',
 'ESPOL、研究团队、创业者及企业。|ESPOL, researchers, entrepreneurs and firms.',
 '培训、咨询和创新项目支持科研知识进入创业与企业应用。|Training, advice and innovation projects support research-based ventures and industrial applications.',
 '官方介绍列明技术转移和创业服务。|The official profile identifies transfer and entrepreneurship services.',
 '参与培训不等于创办了可持续经营企业。|Training participation does not establish a sustainable business.',
 '用客户试用和技术验证筛选后续创业支持。|Use customer trials and technical validation to select further venture support.')
add('cnpem','BR',None,None,'巴西国家能源与材料研究中心开放设施|Brazil CNPEM open research facilities',
 'pilot','materials','https://cnpem.br/en/','CNPEM','en',
 '研究中心结合开放设施、自主科研、创新支持和培训，服务学术与产业用户。|CNPEM combines open facilities, in-house research, innovation support and training for academic and industrial users.',
 'CNPEM、外部高校研究者及企业研发团队。|CNPEM, external academic researchers and industrial R&D teams.',
 '先进设备与专家共同支持材料和能源问题的实验验证。|Advanced equipment and specialists jointly support experimental validation in materials and energy.',
 '官网明确四类职能及对外设施使用安排。|The official site specifies four functions and external facility access.',
 '学术开放使用不代表所有商业保密项目免费。|Academic open access does not mean every confidential commercial project is free.',
 '分别设置开放科研与专有研发的准入和成本规则。|Distinguish access and cost rules for open science and proprietary R&D.',factors=('knowledge','infrastructure','market'))
add('pasteur_labplus','UY',None,None,'蒙得维的亚巴斯德研究所LAB+创业培育|Institut Pasteur Montevideo LAB+ venture building',
 'venture','biomanufacturing','https://pasteur.uy/noticias/lab-del-ip-montevideo-financia-a-4-start-ups-cientificas-uruguayas/','Institut Pasteur de Montevideo','es',
 'LAB+将科学项目、种子投资和运营支持组合，为生物科学创业提供承接载体。|LAB+ combines scientific projects, seed investment and operational support for bioscience ventures.',
 '蒙得维的亚巴斯德研究所、LAB+、科研创业团队及投资伙伴。|Institut Pasteur Montevideo, LAB+, scientific founders and investment partners.',
 '资金与实验基础设施、管理及法律支持共同推进科研创业。|Funding, laboratory infrastructure, management and legal support jointly advance scientific ventures.',
 '2024年官方报道记录首轮支持四家科研初创企业。|A 2024 official account records first-round support for four scientific start-ups.',
 '获得种子投资不证明产品获批或企业盈利。|Seed investment does not establish approval or profitability.',
 '把实验验证、知识产权和商业里程碑同时纳入投资安排。|Include validation, IP and commercial milestones in investment arrangements.',factors=('knowledge','capital','infrastructure'),institutions=('research','ip'))
add('inia_peru','PE',None,None,'秘鲁农业创新技术开发与推广|Peru INIA technology development and extension',
 'capacity','biomanufacturing','https://www.inia.gob.pe/ddta/','INIA Peru','es',
 '技术开发部门组织农业技术验证、推广、技术援助及种子种苗服务。|The development department organises agricultural validation, extension, technical assistance and seed/planting-material services.',
 '秘鲁国家农业创新研究所、研究推广网络和生产者。|Peru’s INIA, research/extension networks and producers.',
 '研究成果通过验证、培训及生产资料服务进入农业应用。|Research enters agriculture through validation, training and production-material services.',
 '官方部门介绍列出技术开发、转移与培训职责。|The official division profile identifies development, transfer and training functions.',
 '推广规模不能单独说明产量或收入提升。|Extension scale alone does not establish yield or income gains.',
 '按当地品种、气候和经营规模安排验证试验。|Design trials around local varieties, climate and farm scale.',factors=('knowledge','talent','market'))
add('proinpa','BO',None,None,'玻利维亚PROINPA农业技术服务|Bolivia PROINPA agricultural technology services',
 'intermediary','biomanufacturing','https://www.proinpa.org/web/servicios/','Fundación PROINPA','es',
 '农业研究基金会以实验室诊断、微生物质量控制及技术培训服务生产者和企业。|PROINPA serves producers and firms through diagnostics, microbial quality control and training.',
 'PROINPA、Agrolab、农业生产者及企业。|PROINPA, Agrolab, agricultural producers and firms.',
 '病虫害诊断与有益微生物评价将研究能力转为可使用的技术服务。|Pest diagnostics and beneficial-microbe assessment turn research capabilities into usable services.',
 '官网服务目录列明分子诊断、微生物与质量评价能力。|The official catalogue identifies molecular diagnostics, microbiology and quality assessment.',
 '实验室评价不能直接替代田间效果验证。|Laboratory assessment cannot replace field validation.',
 '以田间条件和产品质量追踪连接诊断与应用。|Connect diagnostics to use through field conditions and product-quality tracking.')
add('embrapa_open','BR',None,None,'巴西农业研究公司开放研发合作|Embrapa open agricultural R&D collaboration',
 'consortium','biomanufacturing','https://www.embrapa.br/pt/pesquisa','Embrapa','pt',
 '公共农业研究机构以开放创新连接研究能力、共享基础设施和企业伙伴。|A public agricultural research organisation connects research, shared infrastructure and firms through open innovation.',
 '巴西农业研究公司、公共科研机构及私人合作伙伴。|Embrapa, public research organisations and private partners.',
 '联合研发及技术资产管理将研究任务与产业合作连接。|Joint R&D and technology-asset management connect research tasks with industrial collaboration.',
 '官方研究页面明确开放创新、伙伴合作和技术资产安排。|The official research page describes open innovation, partnerships and technology assets.',
 '不能把各研究分支重复视为独立模式。|Research branches should not be counted repeatedly as independent models.',
 '在合作前明确品种、数据和技术资产的使用权。|Specify rights to varieties, data and technology assets before collaboration.',institutions=('research','ip'))
add('inta_transfer','AR',None,None,'阿根廷INTA技术转移与企业接口|Argentina INTA technology transfer and enterprise interface',
 'intermediary','biomanufacturing','https://www.argentina.gob.ar/inta/relaciones/vt','INTA','es',
 '农业技术研究所通过技术组合、知识产权和企业合作推进成果应用。|INTA supports uptake through a technology portfolio, IP management and industrial cooperation.',
 'INTA、技术转移团队、企业和生产者。|INTA, transfer teams, firms and producers.',
 '合作协议、许可和创业培育为不同技术提供承接渠道。|Cooperation agreements, licensing and incubation provide differentiated transfer routes.',
 '官方技术合作页面列明技术组合与成果转移职能。|The official linkage page identifies the technology portfolio and transfer functions.',
 '许可签约不等于最终用户广泛采用。|A licence agreement does not establish broad end-user adoption.',
 '连接研发协议、企业服务和生产者反馈。|Connect research agreements, enterprise services and producer feedback.',institutions=('research','ip'))
add('inia_uruguay_policy','UY',None,None,'乌拉圭INIA联合研发与许可制度|Uruguay INIA joint R&D and licensing framework',
 'consortium','biomanufacturing','https://www.inia.uy/sites/default/files/publications/2024-06/TemaInst1-2010.pdf','INIA Uruguay','es',
 '农业研究机构以技术许可、研发联盟和企业协议连接公共研究与产业。|The agricultural institute links public research to industry through licensing, R&D alliances and enterprise agreements.',
 '乌拉圭国家农业研究所、研发伙伴及获许可企业。|Uruguay’s INIA, research partners and licensees.',
 '知识产权与协议制度支持技术推广及企业共同开发。|IP and agreement rules support diffusion and joint industrial development.',
 '2010年公开文件说明技术转移和企业合作制度。|A public 2010 document explains transfer and industrial cooperation rules.',
 '历史制度文本不代表2026年所有实施安排。|A historical framework does not establish all implementation arrangements in 2026.',
 '区分公共推广职能与具有排他性的商业授权。|Distinguish public extension from exclusive commercial licensing.',institutions=('research','ip'))

add('fenex_crc','AU',None,None,'澳大利亚未来能源出口合作研究中心|Australia Future Energy Exports CRC',
 'consortium','industry','https://www.fenex.org.au/about/','FEnEx CRC','en',
 '合作研究中心联合大学与能源企业，研究液化天然气效率、氢能和出口链数字化。|The CRC joins universities and energy firms on LNG efficiency, hydrogen and export-chain digitalisation.',
 'FEnEx CRC、大学、能源企业及技术供应商。|FEnEx CRC, universities, energy firms and technology suppliers.',
 '产业与科研伙伴共同组织面向能源出口链的长期研发。|Industrial and research partners organise sustained R&D for the energy export chain.',
 '官方介绍列明研究计划、合作组织和技术方向。|The official profile identifies research programmes, partnerships and technical areas.',
 '出口技术研究不证明低排放产品已有稳定市场。|Export research does not establish a sustained market for low-emissions products.',
 '将出口客户要求、技术验证和基础设施约束共同纳入研发。|Include customer requirements, validation and infrastructure constraints in R&D.')
add('crc_time','AU',None,None,'澳大利亚矿区转型合作研究中心|Australia CRC for Transformations in Mining Economies',
 'consortium','industry','https://crctime.com.au/discover-overview/','CRC TiME','en',
 '中心联合矿业、科研、政府和社区，研究矿山关闭及矿区经济转型。|The centre joins mining, research, government and communities on mine closure and regional transition.',
 'CRC TiME、矿业企业、高校、原住民及地方社区。|CRC TiME, mining firms, universities, Indigenous and local communities.',
 '共同研究技术、生态与经济问题，使关闭方案与当地发展衔接。|Joint technical, ecological and economic research links closure plans with local development.',
 '官网确认2020年启动及跨部门研究伙伴安排。|The official site records a 2020 launch and cross-sector research partnerships.',
 '研究联盟不能代替具体矿区的责任和修复资金。|A research alliance cannot replace site-level liabilities and restoration finance.',
 '让社区与矿山责任主体共同定义可验证的转型目标。|Have communities and mine operators jointly define verifiable transition objectives.')
add('minex_crc','AU',None,None,'澳大利亚矿产勘探合作研究中心|Australia MinEx Cooperative Research Centre',
 'consortium','materials','https://minexcrc.com.au/about/','MinEx CRC','en',
 '中心围绕钻探效率、钻探同步数据和全国钻探计划开展产学研合作。|The CRC collaborates on drilling efficiency, data during drilling and the National Drilling Initiative.',
 'MinEx CRC、矿业及设备企业、政府地学机构和高校。|MinEx CRC, mining/equipment firms, geological agencies and universities.',
 '企业工程需求与公共地学数据共同组织研究和现场验证。|Industrial engineering needs and public geoscience data jointly shape research and field validation.',
 '官方介绍列明联合研究计划和勘探技术方向。|The official profile identifies joint programmes and exploration technologies.',
 '研究投入不能直接视为新矿发现或开采收益。|Research inputs are not discoveries or extraction returns.',
 '分别评价设备性能、数据质量和现场成本。|Evaluate equipment performance, data quality and field costs separately.',factors=('knowledge','data','infrastructure'),institutions=('research','data'))
add('smartsat_crc','AU',None,None,'澳大利亚智能卫星合作研究中心|Australia SmartSat CRC',
 'consortium','digital','https://smartsatcrc.com/about/about-us/','SmartSat CRC','en',
 '卫星研究联盟联结大学、科研机构与企业，研究通信、物联网和地球观测服务。|A satellite consortium connects universities, institutes and firms in communications, IoT and Earth-observation services.',
 'SmartSat CRC、大学、研究机构和航天技术企业。|SmartSat CRC, universities, institutes and space-technology firms.',
 '公共支持与联合研发组织专业技术、知识产权和产业能力。|Public support and collaborative R&D combine specialist technologies, IP and industrial capabilities.',
 '官网列明联盟性质及研究方向。|The official site identifies the consortium and research areas.',
 '联盟研究能力不等于全部技术已通过在轨验证。|Research capability does not establish in-orbit validation for every technology.',
 '区分实验室、地面系统与在轨验证里程碑。|Distinguish laboratory, ground-system and in-orbit milestones.',institutions=('research','ip'))
add('anff','AU',None,None,'澳大利亚国家微纳加工开放设施|Australian National Fabrication Facility',
 'pilot','materials','https://anff.org.au/','ANFF','en',
 '微纳加工设施网络向科研与产业用户提供设备、工艺专家和培训。|The fabrication network gives research and industry users equipment, process specialists and training.',
 'ANFF、大学设施团队、研究人员及企业。|ANFF, university facility teams, researchers and firms.',
 '用户可直接使用设施或委托技术服务，降低专用设备投入门槛。|Direct access or fee-for-service work reduces barriers to specialised equipment.',
 '官方页面明确开放使用及专业技术支持方式。|The official page specifies access and specialist support routes.',
 '开放准入仍需安全培训、排期及适当收费。|Open access still requires safety training, scheduling and appropriate fees.',
 '把设备能力、工艺支持和企业交付周期结合。|Combine equipment capability, process support and industrial delivery schedules.',factors=('knowledge','infrastructure','talent'))
add('ansto_industry','AU',None,None,'澳大利亚核科学机构产业设施服务|ANSTO industrial research-facility access',
 'pilot','materials','https://www.ansto.gov.au/work-with-us/industry','ANSTO','en',
 '科研设施与专家团队支持企业材料、制造及食品问题的测试与研发。|Research facilities and specialists support industrial testing and R&D in materials, manufacturing and food.',
 'ANSTO、企业研发团队及新南威尔士州技术支持计划。|ANSTO, industrial R&D teams and NSW technology-support programmes.',
 '设施服务与企业合作结合，部分中小企业项目可通过配套资助接入。|Facility services link to partnerships, with matched support available for some SME projects.',
 '官方产业页面列明设施、合作及技术券支持。|The official industry page identifies facilities, collaboration and voucher support.',
 '有条件资助不能视为所有产业服务免费。|Conditional support does not mean all industrial services are free.',
 '按技术问题选择设施并预先约定交付和数据权益。|Select facilities by technical need and agree deliverables and data rights in advance.',factors=('knowledge','infrastructure','capital'))
add('food_agility','AU',None,None,'澳大利亚食品农业敏捷研发计划|Food Agility CRC agile research model',
 'consortium','digital','https://www.foodagility.com/posts/introducing-our-new-research-agility-model','Food Agility CRC','en',
 '食品农业研发计划通过敏捷研究将数字技术与企业生产场景结合。|The programme uses agile research to connect digital technologies with food/agriculture operations.',
 'Food Agility CRC、科研团队和农业食品企业。|Food Agility CRC, research teams and food/agriculture firms.',
 '分阶段研究、设计思维和迭代试验让企业持续参与需求定义。|Staged research, design thinking and iterative trials sustain industrial participation in defining needs.',
 '2020年官方说明发布研究敏捷性框架。|A 2020 official account publishes the research-agility framework.',
 '迭代框架本身不能证明收入增长或资源节约。|An iterative framework does not itself establish revenue growth or resource savings.',
 '用短周期试验检验数据质量和经营决策价值。|Use short trials to test data quality and operational decision value.',factors=('knowledge','data','market'),institutions=('research','data'))
add('amgc','AU',None,None,'澳大利亚先进制造联合投资项目|Australia AMGC manufacturing co-investment',
 'capacity','manufacturing','https://amgc.org.au/projects/','AMGC','en',
 '项目机制通过产业联合投资和科研合作支持制造技术商业化。|The programme supports manufacturing commercialisation through industrial co-investment and research collaboration.',
 '先进制造增长中心、制造企业及科研伙伴。|AMGC, manufacturers and research partners.',
 '企业共同投入并结合研究能力，推进产品与生产工艺开发。|Industrial co-investment combines with research capability for product and process development.',
 '官方项目目录列明受支持项目及伙伴。|The official portfolio identifies supported projects and partners.',
 '预测就业和收入不等于已经实现的成效。|Forecast employment and revenue are not realised outcomes.',
 '共同投资应与技术验收和客户应用节点对应。|Link co-investment to technical acceptance and customer applications.',factors=('knowledge','capital','market'))
add('battery_crc','AU',None,None,'澳大利亚未来电池产业合作研究计划|Australia Future Battery Industries CRC programme',
 'consortium','materials','https://www.mriwa.wa.gov.au/research-projects/project-portfolio/future-battery-industries-cooperative-research-centre/','MRIWA','en',
 '合作研究计划围绕电池价值链组织产业、政府和科研投入。|The CRC programme combines industrial, government and research inputs across the battery value chain.',
 '未来电池产业CRC、MRIWA、大学及产业伙伴。|Future Battery Industries CRC, MRIWA, universities and industrial partners.',
 '跨机构共同研究连接矿物加工、电池材料及产业能力建设。|Joint research connects mineral processing, battery materials and industrial capability development.',
 '官方项目记录给出2019至2025年项目期及支持安排。|The official project record specifies a 2019–2025 period and support arrangements.',
 '历史项目期不能作为2026年持续运行的证明。|The historical period does not establish continued operation in 2026.',
 '按原料、材料和制造环节设置可交付研究节点。|Set deliverable milestones for feedstocks, materials and manufacturing.',period=(2019,2025))
add('robinson','NZ',None,None,'新西兰罗宾逊研究所超导工程合作|New Zealand Robinson superconducting engineering collaboration',
 'intermediary','materials','https://robinson.ac.nz/research/RobinsonResearchInstitute.pdf','Robinson Research Institute','en',
 '研究所把超导、低温及材料研究与工业工程和商业化合作结合。|The institute connects superconductivity, cryogenics and materials research with industrial engineering and commercialisation.',
 '惠灵顿维多利亚大学罗宾逊研究所及产业伙伴。|Victoria University of Wellington’s Robinson institute and industrial partners.',
 '物理与工程团队共同面向设备和电气应用开展研发。|Physics and engineering teams jointly undertake R&D for equipment and electrical applications.',
 '官方研究所资料介绍产业协作及超导应用方向。|Official institute material identifies industrial collaboration and superconducting applications.',
 '先进材料性能不等于整套设备具有经济优势。|Material performance does not establish system-level economic advantage.',
 '把材料验证延伸至设备效率、可靠性和维护。|Extend validation to equipment efficiency, reliability and maintenance.')
add('ferrier','NZ',None,None,'新西兰费里尔研究所合同研发|New Zealand Ferrier Institute contract research',
 'intermediary','biomanufacturing','https://www.wgtn.ac.nz/ferrier/work-with-us','Victoria University of Wellington','en',
 '大学研究所为外部客户提供化学研发，以合同安排衔接科学研究与产品开发。|A university institute offers chemistry R&D through contracts connecting science and product development.',
 '费里尔研究所、客户企业及科研合作方。|Ferrier Research Institute, client companies and research partners.',
 '保密协议、工作范围、预算及许可安排明确研发交付。|NDAs, scopes of work, budgets and licensing clarify research deliverables.',
 '官方合作页面说明合同研究和知识产权合作流程。|The official collaboration page describes contract research and IP arrangements.',
 '合同研发仍面临技术不确定性和客户监管要求。|Contract R&D remains subject to technical uncertainty and client regulatory requirements.',
 '预先约定背景知识产权、研发成果及后续使用权。|Agree background IP, research outputs and subsequent rights in advance.',institutions=('research','ip'))
add('epecentre','NZ',None,None,'新西兰电力工程产学研中心|New Zealand Electric Power Engineering Centre',
 'consortium','industry','https://www.canterbury.ac.nz/research/about-uc-research/research-groups-and-centres/electric-power-engineering-centre/about-epecentre','University of Canterbury','en',
 '电力工程中心将行业合作、研究与专业人才培养配置在大学平台。|The centre combines industry cooperation, research and professional education in a university platform.',
 '坎特伯雷大学、电力行业及电力工程教育信托。|University of Canterbury, the power industry and the Power Engineering Excellence Trust.',
 '大学与行业共同支持研究、合同服务及工程教育。|University and industry jointly support research, contract services and engineering education.',
 '官方介绍记录2002年建立的大学与行业共同倡议。|The official profile records the joint university–industry initiative established in 2002.',
 '人才培养效果与具体技术商业化应分别评价。|Education outcomes and technology commercialisation should be assessed separately.',
 '把行业研究任务与工程师培养连续衔接。|Maintain links between industrial research tasks and engineer development.',factors=('knowledge','talent','market'))
add('lincoln_agritech','NZ',None,None,'新西兰林肯农业工程应用研究|New Zealand Lincoln Agritech applied research',
 'intermediary','biomanufacturing','https://lincolnagritech.co.nz/about-us/','Lincoln Agritech','en',
 '大学所有的独立研发机构把传感、农业工程、生物技术和材料研究对接产业问题。|A university-owned independent R&D organisation connects sensing, agricultural engineering, biotechnology and materials with industry.',
 'Lincoln Agritech、林肯大学、农业及材料企业。|Lincoln Agritech, Lincoln University and agricultural/materials firms.',
 '跨学科研发和场景试验将科学能力转化为企业技术方案。|Interdisciplinary research and contextual trials turn science into industrial solutions.',
 '官方介绍说明组织性质和农业、环境及材料方向。|The official profile specifies its organisational form and agricultural, environmental and materials work.',
 '田间结果受季节、土壤与经营条件影响。|Field results depend on seasons, soils and operating conditions.',
 '用多场景测试验证技术的适用范围。|Use multi-setting trials to establish applicability.',factors=('knowledge','data','market'))
add('sros_pilot','WS',None,None,'萨摩亚科研组织产品中试平台|Samoa SROS product-development piloting',
 'pilot','biomanufacturing','https://www.sros.org.ws/our-divisions/pidd/','SROS','en',
 '产品创新部门通过实验室和中试操作，把本地农产及自然资源研发转向增值产品。|The division uses laboratories and piloting to develop value-added products from local agriculture and natural resources.',
 '萨摩亚科学研究组织、产品研发及中试团队、产业伙伴。|SROS, product/pilot teams and industrial partners.',
 '研发、原型加工与企业协调形成从资源到产品的应用链。|Research, prototyping and industry coordination connect resources to products.',
 '官方部门页面列明产品开发与中试职责。|The official division page identifies product-development and pilot functions.',
 '小批量试制不证明出口认证或稳定市场。|Small-batch pilots do not establish export certification or a sustained market.',
 '以小规模原料供应、食品规范和运输成本设计工艺。|Design processes around small feedstock volumes, food rules and transport costs.',factors=('knowledge','infrastructure','market'))
add('png_atcdi','PG',None,None,'巴布亚新几内亚适用技术研究与推广|Papua New Guinea appropriate-technology development and extension',
 'capacity','manufacturing','https://www.unitech.ac.pg/wp-content/uploads/2023/04/PNGUoT_Research_Report_2022.pdf','Papua New Guinea University of Technology','en',
 '大学适用技术机构围绕能源、水卫生、小工业和食品加工提供研发及技术服务。|A university appropriate-technology institute provides R&D and services in energy, water/sanitation, small industry and food processing.',
 '巴布亚新几内亚科技大学ATCDI、项目委托方及社区产业用户。|PNGUoT’s ATCDI, project clients and community/industrial users.',
 '利益相关方提出需求，大学工程团队以研究、培训和技术咨询回应。|Stakeholders propose needs and university engineers respond through research, training and technical advice.',
 '大学2022年研究报告记录该机构职责和项目工作。|The university’s 2022 research report documents its mandate and project work.',
 '历史年度记录不证明所有项目目前仍在运行。|A historical annual record does not establish ongoing operation of every project.',
 '在设计中优先考虑维修技能、备件和社区运行条件。|Prioritise repair skills, spare parts and community operating conditions.',factors=('knowledge','talent','infrastructure'))

def profile(key, title, model, keys, mechanism, conditions, factors, government, boundary, province=None):
    row=dict(id=key,name=bi(title),archetype=model,case_ids=['oi_'+k for k in keys],
        **{k:bi(v) for k,v in zip(('mechanism','conditions','factors','government','boundary'),
                                  (mechanism,conditions,factors,government,boundary))})
    if province: row['province']=province
    PROFILES.append(row)

profile('resource_materials_regions','中国资源地区：专业研究与材料工程|Chinese resource regions: specialist research and materials engineering','cluster',
 ['baotou_rareearth','ganjiang_engineering','yunnan_material_genome'],
 '以稀土、矿物和稀贵金属产业问题连接地方研究机构、企业与工程平台。|Resource-industry problems connect local research institutions, firms and engineering platforms.',
 '有可持续的产业需求、专业研究团队及材料测试能力。|Sustained industrial demand, specialist teams and materials testing.',
 '资源禀赋提供研究场景，但工程人才、材料数据和客户认证决定技术能否被采用。|Resources provide settings; engineers, materials data and customer qualification shape uptake.',
 '支持共享测试、真实原料试验和成果交易，按工艺性能验收。|Support shared testing, actual-feedstock trials and technology transactions with process-based acceptance.',
 '内蒙古、江西和云南案例机制并不相同，资源储量本身不是创新绩效。|Mechanisms differ across Inner Mongolia, Jiangxi and Yunnan; resource stocks are not innovation performance.')
profile('northeast_engineering','东北案例：工艺中试与装备协作|Northeast China: process piloting and equipment collaboration','pilot',
 ['ciac_pilot','sanjiang_fungi','harbin_fusion'],
 '以专业中试承接工艺放大，以联合研发组织复杂装备研究。|Specialist pilots support scale-up while alliances organise complex equipment research.',
 '具备持续运行的设施团队、工程企业和明确技术需求。|Operating facility teams, engineering firms and defined technical needs.',
 '工业与科研积累有助于工程验证；生物工艺和聚变装备的成熟周期差异很大。|Industrial/research capabilities help validation, but bioprocess and fusion equipment have very different timelines.',
 '支持中试操作队伍、关键部件测试及企业共同定义任务。|Support pilot operators, component testing and company-defined tasks.',
 '三个案例说明不同接口，不能据此概括整个东北或宣称聚变商业化。|Three cases illustrate interfaces, not all Northeast China or commercial fusion.')
profile('western_bioresources','西部特色生物资源：研究与应用衔接|Western Chinese bioresources: research-to-use interfaces','consortium',
 ['tibet_yak','xinjiang_medicine','yunnan_boton'],
 '围绕育种、民族药和香料资源，结合科研能力、质量平台及企业应用。|Breeding, ethnic medicines and fragrances combine research, quality platforms and industrial applications.',
 '有资源合规利用、专业团队、监管知识和稳定质量控制。|Lawful resource use, specialist teams, regulatory knowledge and reliable quality control.',
 '地方资源需要经过可复现工艺和质量验证，不能直接等同于商业优势。|Resources need reproducible processes and quality validation before becoming commercial advantages.',
 '支持资源溯源、检测、中试与企业联合验证。|Support traceability, testing, pilots and joint industrial validation.',
 '畜牧、药品和香料的监管路径不同，不宜共用单一商业化标准。|Livestock, medicines and fragrances have different regulatory pathways.')
profile('fujian_joint_pilots','福建案例：共建中试与企业出题|Fujian cases: joint pilots and company-defined research','pilot',
 ['jiageng_lab','qingyuan_lab','mindu_lab'],
 '实验室共享能力与企业联合研发并行，按材料或器件任务组织验证和转化。|Shared laboratories and joint industrial R&D organise validation and transfer around materials/devices.',
 '具有产业客户、专业工艺人员及可开放使用的设施。|Industrial customers, process specialists and accessible facilities.',
 '材料研究积累与企业验证互补，中试和市场认证不能由论文替代。|Materials research complements industrial validation; papers cannot replace pilots or market qualification.',
 '明确共建成本、平台准入和成果产权，按工程节点释放支持。|Clarify co-funding, access and IP, releasing support against engineering milestones.',
 '案例反映三类实验室接口，不代表福建所有行业只有一种模式。|These laboratory interfaces are not a single model for every Fujian industry.',province='CN-FJ')
profile('engineering_digital_centres','中部案例：数字工程与产业联合任务|Central China: digital engineering and industrial joint tasks','consortium',
 ['digital_design_centre','digital_construction_centre','xiangjiang_energy','jianghuai_medrobot'],
 '公司、联盟或合作项目连接数字研究、工业数据和工程场景。|Companies, alliances or projects connect digital research, industrial data and engineering settings.',
 '有可信数据授权、工程业主和现场验证能力。|Trusted data permissions, asset operators and field-validation capability.',
 '行业数据和工程知识比单纯算法数量更能约束实际应用。|Domain data and engineering knowledge constrain applications more directly than algorithm counts.',
 '以可验证场景组织任务，明确数据、知识产权和安全责任。|Organise verifiable applications with explicit data, IP and safety responsibilities.',
 '装备制造、建筑、能源和医疗不可用同一验收指标；部分合作仍处协议阶段。|Manufacturing, construction, energy and medicine need different acceptance measures; some partnerships remain agreements.')
profile('african_public_engineering','非洲案例：公共工程能力与企业技术服务|African cases: public engineering capacity and firm services','intermediary',
 ['bitri','kirdi','uiri','tirdo_pilot','csir_iir'],
 '公共研究机构共享试验、中试与工程能力，降低企业自建设施的门槛。|Public institutes share testing, piloting and engineering capacity, reducing firms’ facility barriers.',
 '有维护经费、操作人才和真实企业需求，而非只购置设备。|Maintenance funding, operators and genuine industrial demand, not equipment alone.',
 '小企业吸收能力、备件和质量体系影响公共设施能否发挥作用。|SME absorptive capacity, spares and quality systems shape facility usefulness.',
 '把设施维护、操作培训和企业交付共同纳入服务合同。|Include maintenance, operator training and industrial deliverables in service contracts.',
 '五国机构案例不是整个非洲的统一模式，服务清单不等于已测得生产率收益。|Institutes in five countries do not define all Africa; service lists are not measured productivity gains.')
profile('latin_agri_networks','拉美农业：研究推广与产业授权|Latin American agriculture: extension and industrial licensing','capacity',
 ['agrosavia','inia_peru','embrapa_open','inta_transfer','proinpa'],
 '农业研究通过区域验证、技术服务、联合研发和许可连接生产者与企业。|Agricultural research connects producers and firms through regional trials, services, joint R&D and licensing.',
 '具备长期田间研究、地方推广网络和种质及知识产权规则。|Long-term field research, local extension and germplasm/IP rules.',
 '气候、品种、经营规模和生产者能力决定技术适配，推广与商业授权互补。|Climate, varieties, farm scale and skills shape adaptation; extension complements commercial licensing.',
 '支持跨季节验证与生产者反馈，分别管理公共推广和专有授权。|Support multi-season validation and feedback; manage public extension separately from proprietary licences.',
 '不同国家制度和生产条件不同，不能把推广覆盖当作收入增量。|Institutions and production conditions differ; extension coverage is not incremental income.')
profile('shared_science_facilities','跨区域机制：共享科学设施与产业研发|Cross-regional mechanism: shared science facilities and industrial R&D','pilot',
 ['cnpem','anff','ansto_industry'],
 '先进设备与专业人员一起开放，支持外部科研与企业测试、加工和研发。|Advanced equipment and specialists support external research and industrial testing, fabrication and R&D.',
 '具备稳定运维、专业技术支持及清楚的开放与保密规则。|Stable operations, technical support and clear open/confidential access rules.',
 '高固定成本设施适合共享，但排期、收费与知识产权影响企业使用。|High-fixed-cost facilities suit sharing, while scheduling, fees and IP shape industrial access.',
 '区分开放科学和商业委托，支持中小企业明确界限的首次使用。|Separate open science from commercial commissions; support bounded first use by SMEs.',
 '巴西与澳大利亚案例用于机制对照，不按设施规模排列国家优劣。|Brazilian and Australian cases compare mechanisms, not national performance by facility size.')
profile('pacific_adaptation','太平洋岛屿案例：小规模加工与适用工程|Pacific island cases: small-scale processing and appropriate engineering','capacity',
 ['sros_pilot','png_atcdi'],
 '大学或公共研究团队通过产品中试、工程咨询和培训回应本地需求。|University/public teams respond to local needs with product pilots, engineering advice and training.',
 '工艺适配原料规模、运输条件和可获得的维护技能。|Processes fit feedstock volumes, transport and available maintenance skills.',
 '小市场和分散供应提高规模化成本，简单可靠的工程方案可能更适用。|Small markets and dispersed supply raise scale-up costs; reliable simpler engineering may fit better.',
 '支持原型试用、质量检测和本地操作培训，重视持续运行成本。|Support prototypes, quality testing and local training, accounting for sustained operating costs.',
 '萨摩亚与巴新案例不足以代表所有岛屿经济体，历史记录不等于当前项目状态。|Samoa and PNG cannot represent all island economies; historical records do not establish current project status.')
profile('energy_joint_operators','能源联合研发：合资公司与合同联盟|Joint energy R&D: joint companies and contractual consortia','consortium',
 ['ytec','fenex_crc','battery_crc'],
 '合资研发公司与合作研究中心分别以股权或长期合同协调能源技术研究。|Joint companies and CRCs coordinate energy R&D through ownership or long-term contracts.',
 '有稳定产业需求、长期资金和科研企业之间清晰的权责。|Stable industrial demand, long-term funding and clear research–industry responsibilities.',
 '资本和工程场景互补，但技术路线变化会改变合作价值。|Capital complements engineering settings, while technological shifts alter partnership value.',
 '按技术成熟度安排阶段考核，明确成果权利及合作退出条件。|Stage reviews by readiness and clarify results ownership and exit conditions.',
 '不同国家治理和项目周期不同，联合投入并不保证技术成功。|Governance and programme periods differ; joint inputs do not guarantee technical success.')

def main():
    from collections import Counter
    payload=dict(schema_version='1.0',reviewed_at=DATE,cases=CASES,sources=SOURCES,
        sector_taxonomy=SECTORS,model_profiles=PROFILES,
        provenance=dict(expansion_review=dict(reviewed_at=DATE,
            selection='Named independent programmes, collaborations or platforms from official sources; thin regions prioritised.',
            limitations='Purposive evidence sample, not a global census or innovation-performance ranking. Historical sources are identified in observed/constraints; inaccessible pages may be supported by indexed official excerpts.',
            interpretation_fields=['constraints','transfer','primary_model','model_profiles'])))
    target=ROOT/'config/open_innovation_expansion.json'
    target.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(dict(cases=len(CASES),sources=len(SOURCES),profiles=len(PROFILES),
        countries=dict(Counter(c['countries'][0] for c in CASES))),ensure_ascii=False))

if __name__=='__main__': main()
